INSERT INTO exercises (name, category, is_public, equipment, level, force, mechanic, instructions, primary_muscles, secondary_muscles, coaching_cues, common_mistakes)
VALUES ('Thigh Abductor', 'machine', true, 'machine', 'beginner', 'push', 'isolation', ARRAY['To begin, sit down on the abductor machine and select a weight you are comfortable with. When your legs are positioned properly, grip the handles on each side. Your entire upper body (from the waist up) should be stationary. This is the starting position.','Slowly press against the machine with your legs to move them away from each other while exhaling.','Feel the contraction for a second and begin to move your legs back to the starting position while breathing in. Note: Remember to keep your upper body stationary to prevent any injuries from occurring.','Repeat for the recommended amount of repetitions.'], ARRAY['abductors'], ARRAY['glutes'], ARRAY[]::TEXT[], ARRAY[]::TEXT[])
ON CONFLICT DO NOTHING;

INSERT INTO exercises (name, category, is_public, equipment, level, force, mechanic, instructions, primary_muscles, secondary_muscles, coaching_cues, common_mistakes)
VALUES ('Thigh Adductor', 'machine', true, 'machine', 'beginner', 'pull', 'isolation', ARRAY['To begin, sit down on the adductor machine and select a weight you are comfortable with. When your legs are positioned properly on the leg pads of the machine, grip the handles on each side. Your entire upper body (from the waist up) should be stationary. This is the starting position.','Slowly press against the machine with your legs to move them towards each other while exhaling.','Feel the contraction for a second and begin to move your legs back to the starting position while breathing in. Note: Remember to keep your upper body stationary and avoid fast jerking motions in order to prevent any injuries from occurring.','Repeat for the recommended amount of repetitions.'], ARRAY['adductors'], ARRAY['glutes','hamstrings'], ARRAY[]::TEXT[], ARRAY[]::TEXT[])
ON CONFLICT DO NOTHING;

INSERT INTO exercises (name, category, is_public, equipment, level, force, mechanic, instructions, primary_muscles, secondary_muscles, coaching_cues, common_mistakes)
VALUES ('Tire Flip', 'other', true, 'other', 'intermediate', 'pull', 'compound', ARRAY['Begin by gripping the bottom of the tire on the tread, and position your feet back a bit. Your chest should be driving into the tire.','To lift the tire, extend through the hips, knees, and ankles, driving into the tire and up.','As the tire reaches a 45 degree angle, step forward and drive a knee into the tire. As you do so adjust your grip to the upper portion of the tire and push it forward as hard as possible to complete the turn. Repeat as necessary.'], ARRAY['quadriceps'], ARRAY['calves','chest','forearms','glutes','hamstrings','lower back','shoulders','traps','triceps'], ARRAY[]::TEXT[], ARRAY[]::TEXT[])
ON CONFLICT DO NOTHING;

INSERT INTO exercises (name, category, is_public, equipment, level, force, mechanic, instructions, primary_muscles, secondary_muscles, coaching_cues, common_mistakes)
VALUES ('Trail Running/Walking', 'body only', true, 'body only', 'beginner', NULL, NULL, ARRAY['Running or hiking on trails will get the blood pumping and heart beating almost immediately. Make sure you have good shoes. While you use the muscles in your calves and buttocks to pull yourself up a hill, the knees, joints and ankles absorb the bulk of the pounding coming back down. Take smaller steps as you walk downhill, keep your knees bent to reduce the impact and slow down to avoid falling.','A 150 lb person can burn over 200 calories for 30 minutes walking uphill, compared to 175 on a flat surface. If running the trail, a 150 lb person can burn well over 500 calories in 30 minutes.'], ARRAY['quadriceps'], ARRAY['calves','glutes','hamstrings'], ARRAY[]::TEXT[], ARRAY[]::TEXT[])
ON CONFLICT DO NOTHING;

INSERT INTO exercises (name, category, is_public, equipment, level, force, mechanic, instructions, primary_muscles, secondary_muscles, coaching_cues, common_mistakes)
VALUES ('Trap Bar Deadlift', 'other', true, 'other', 'beginner', 'pull', 'compound', ARRAY['For this exercise load a trap bar, also known as a hex bar, to an appropriate weight resting on the ground. Stand in the center of the apparatus and grasp both handles.','Lower your hips, look forward with your head and keep your chest up.','Begin the movement by driving through the heels and extend your hips and knees. Avoid rounding your back at all times.','At the completion of the movement, lower the weight back to the ground under control.'], ARRAY['quadriceps'], ARRAY['glutes','hamstrings'], ARRAY[]::TEXT[], ARRAY[]::TEXT[])
ON CONFLICT DO NOTHING;

INSERT INTO exercises (name, category, is_public, equipment, level, force, mechanic, instructions, primary_muscles, secondary_muscles, coaching_cues, common_mistakes)
VALUES ('Tricep Dumbbell Kickback', 'dumbbell', true, 'dumbbell', 'beginner', 'push', 'isolation', ARRAY['Start with a dumbbell in each hand and your palms facing your torso. Keep your back straight with a slight bend in the knees and bend forward at the waist. Your torso should be almost parallel to the floor. Make sure to keep your head up. Your upper arms should be close to your torso and parallel to the floor. Your forearms should be pointed towards the floor as you hold the weights. There should be a 90-degree angle formed between your forearm and upper arm. This is your starting position.','Now, while keeping your upper arms stationary, exhale and use your triceps to lift the weights until the arm is fully extended. Focus on moving the forearm.','After a brief pause at the top contraction, inhale and slowly lower the dumbbells back down to the starting position.','Repeat the movement for the prescribed amount of repetitions.'], ARRAY['triceps'], ARRAY[]::TEXT[], ARRAY[]::TEXT[], ARRAY[]::TEXT[])
ON CONFLICT DO NOTHING;

INSERT INTO exercises (name, category, is_public, equipment, level, force, mechanic, instructions, primary_muscles, secondary_muscles, coaching_cues, common_mistakes)
VALUES ('Triceps Overhead Extension with Rope', 'cable', true, 'cable', 'beginner', 'push', 'isolation', ARRAY['Attach a rope to a low pulley. After selecting an appropriate weight, grasp the rope with both hands and face away from the cable.','Position your hands behind your head with your elbows point straight up. Your elbows should start out flexed, and you can stagger your stance and lean gently away from the machine to create greater stability. This will be your starting position.','To perform the movement, extend through the elbow while keeping the upper arm in position, raising your hands above your head.','Squeeze your triceps at the top of the movement, and slowly lower the weight back to the start position.'], ARRAY['triceps'], ARRAY[]::TEXT[], ARRAY[]::TEXT[], ARRAY[]::TEXT[])
ON CONFLICT DO NOTHING;

INSERT INTO exercises (name, category, is_public, equipment, level, force, mechanic, instructions, primary_muscles, secondary_muscles, coaching_cues, common_mistakes)
VALUES ('Triceps Pushdown', 'cable', true, 'cable', 'beginner', 'push', 'isolation', ARRAY['Attach a straight or angled bar to a high pulley and grab with an overhand grip (palms facing down) at shoulder width.','Standing upright with the torso straight and a very small inclination forward, bring the upper arms close to your body and perpendicular to the floor. The forearms should be pointing up towards the pulley as they hold the bar. This is your starting position.','Using the triceps, bring the bar down until it touches the front of your thighs and the arms are fully extended perpendicular to the floor. The upper arms should always remain stationary next to your torso and only the forearms should move. Exhale as you perform this movement.','After a second hold at the contracted position, bring the bar slowly up to the starting point. Breathe in as you perform this step.','Repeat for the recommended amount of repetitions.'], ARRAY['triceps'], ARRAY[]::TEXT[], ARRAY[]::TEXT[], ARRAY[]::TEXT[])
ON CONFLICT DO NOTHING;

INSERT INTO exercises (name, category, is_public, equipment, level, force, mechanic, instructions, primary_muscles, secondary_muscles, coaching_cues, common_mistakes)
VALUES ('Triceps Pushdown - Rope Attachment', 'cable', true, 'cable', 'beginner', 'push', 'isolation', ARRAY['Attach a rope attachment to a high pulley and grab with a neutral grip (palms facing each other).','Standing upright with the torso straight and a very small inclination forward, bring the upper arms close to your body and perpendicular to the floor. The forearms should be pointing up towards the pulley as they hold the rope with the palms facing each other. This is your starting position.','Using the triceps, bring the rope down as you bring each side of the rope to the side of your thighs. At the end of the movement the arms are fully extended and perpendicular to the floor. The upper arms should always remain stationary next to your torso and only the forearms should move. Exhale as you perform this movement.','After holding for a second, at the contracted position, bring the rope slowly up to the starting point. Breathe in as you perform this step.','Repeat for the recommended amount of repetitions.'], ARRAY['triceps'], ARRAY[]::TEXT[], ARRAY[]::TEXT[], ARRAY[]::TEXT[])
ON CONFLICT DO NOTHING;

INSERT INTO exercises (name, category, is_public, equipment, level, force, mechanic, instructions, primary_muscles, secondary_muscles, coaching_cues, common_mistakes)
VALUES ('Triceps Pushdown - V-Bar Attachment', 'cable', true, 'cable', 'beginner', 'push', 'isolation', ARRAY['Attach a V-Bar to a high pulley and grab with an overhand grip (palms facing down) at shoulder width.','Standing upright with the torso straight and a very small inclination forward, bring the upper arms close to your body and perpendicular to the floor. The forearms should be pointing up towards the pulley as they hold the bar. The thumbs should be higher than the small finger. This is your starting position.','Using the triceps, bring the bar down until it touches the front of your thighs and the arms are fully extended perpendicular to the floor. The upper arms should always remain stationary next to your torso and only the forearms should move. Exhale as you perform this movement.','After a second hold at the contracted position, bring the V-Bar slowly up to the starting point. Breathe in as you perform this step.','Repeat for the recommended amount of repetitions.'], ARRAY['triceps'], ARRAY[]::TEXT[], ARRAY[]::TEXT[], ARRAY[]::TEXT[])
ON CONFLICT DO NOTHING;

INSERT INTO exercises (name, category, is_public, equipment, level, force, mechanic, instructions, primary_muscles, secondary_muscles, coaching_cues, common_mistakes)
VALUES ('Tuck Crunch', 'body only', true, 'body only', 'beginner', 'pull', 'isolation', ARRAY['To begin, lie down on the floor or an exercise mat with your back pressed against the floor. Your arms should be lying across your sides with the palms facing down.','Your legs should be crossed by wrapping one ankle around the other. Slowly elevate your legs up in the air until your thighs are perpendicular to the floor with a slight bend at the knees. Note: Your knees and toes should be parallel to the floor as opposed to the thighs.','Move your arms from the floor and cross them so they are resting on your chest. This is the starting position.','While keeping your lower back pressed against the floor, slowly lift your torso. Remember to exhale while perform this part of the exercise.','Slowly begin to lower your torso back down to the starting position while inhaling.','Repeat for the recommended amount of repetitions.'], ARRAY['abdominals'], ARRAY[]::TEXT[], ARRAY[]::TEXT[], ARRAY[]::TEXT[])
ON CONFLICT DO NOTHING;

INSERT INTO exercises (name, category, is_public, equipment, level, force, mechanic, instructions, primary_muscles, secondary_muscles, coaching_cues, common_mistakes)
VALUES ('Two-Arm Dumbbell Preacher Curl', 'dumbbell', true, 'dumbbell', 'beginner', 'pull', 'isolation', ARRAY['Grab a dumbbell with each arm and place the upper arms on top of the preacher bench or the incline bench. The dumbbell should be held at shoulder length. This will be your starting position.','As you breathe in, slowly lower the dumbbells until your upper arm is extended and the biceps is fully stretched.','As you exhale, use the biceps to curl the weights up until your biceps is fully contracted and the dumbbells are at shoulder height.','Squeeze the biceps hard for a second at the contracted position and repeat for the recommended amount of repetitions.'], ARRAY['biceps'], ARRAY[]::TEXT[], ARRAY[]::TEXT[], ARRAY[]::TEXT[])
ON CONFLICT DO NOTHING;

INSERT INTO exercises (name, category, is_public, equipment, level, force, mechanic, instructions, primary_muscles, secondary_muscles, coaching_cues, common_mistakes)
VALUES ('Two-Arm Kettlebell Clean', 'kettlebells', true, 'kettlebells', 'intermediate', 'pull', 'compound', ARRAY['Place two kettlebells between your feet. To get in the starting position, push your butt back and look straight ahead.','Clean the kettlebells to your shoulders by extending through the legs and hips as you raise the kettlebells towards your shoulders. Rotate your wrists as you do so.','Lower the kettlebells back to the starting position and repeat.'], ARRAY['shoulders'], ARRAY['calves','glutes','hamstrings','lower back','traps'], ARRAY[]::TEXT[], ARRAY[]::TEXT[])
ON CONFLICT DO NOTHING;

INSERT INTO exercises (name, category, is_public, equipment, level, force, mechanic, instructions, primary_muscles, secondary_muscles, coaching_cues, common_mistakes)
VALUES ('Two-Arm Kettlebell Jerk', 'kettlebells', true, 'kettlebells', 'intermediate', 'push', 'compound', ARRAY['Clean two kettlebells to your shoulders. Clean the kettlebells to your shoulders by extending through the legs and hips as you swing the kettlebells towards your shoulders. Rotate your wrists as you do so, so that the palms face forward. Squat down a few inches and reverse the motion rapidly driving both kettlebells overhead. Immediately after the initial push, squat down again and get under the kettlebells. Once the kettlebells are locked out, stand upright to complete the exercise.'], ARRAY['shoulders'], ARRAY['calves','quadriceps','triceps'], ARRAY[]::TEXT[], ARRAY[]::TEXT[])
ON CONFLICT DO NOTHING;

INSERT INTO exercises (name, category, is_public, equipment, level, force, mechanic, instructions, primary_muscles, secondary_muscles, coaching_cues, common_mistakes)
VALUES ('Two-Arm Kettlebell Military Press', 'kettlebells', true, 'kettlebells', 'intermediate', 'push', 'compound', ARRAY['Clean two kettlebells to your shoulders. Clean the kettlebells to your shoulders by extending through the legs and hips as you swing the kettlebells towards your shoulders. Rotate your wrists as you do so, so that the palms face forward.','Press the kettlebells up and out. As the kettlebells pass your head, lean into the weights so that the kettlebells are racked behind your head. Make sure to contract your lats, butt, and stomach for added stability.'], ARRAY['shoulders'], ARRAY['triceps'], ARRAY[]::TEXT[], ARRAY[]::TEXT[])
ON CONFLICT DO NOTHING;

INSERT INTO exercises (name, category, is_public, equipment, level, force, mechanic, instructions, primary_muscles, secondary_muscles, coaching_cues, common_mistakes)
VALUES ('Two-Arm Kettlebell Row', 'kettlebells', true, 'kettlebells', 'intermediate', 'pull', 'compound', ARRAY['Place two kettlebells in front of your feet. Bend your knees slightly and then push your butt out as much as possible as you bend over to get in the starting position.','Grab both kettlebells and pull them to your stomach, retracting your shoulder blades and flexing the elbows. Keep your back straight. Lower and repeat.'], ARRAY['middle back'], ARRAY['biceps','lats'], ARRAY[]::TEXT[], ARRAY[]::TEXT[])
ON CONFLICT DO NOTHING;

INSERT INTO exercises (name, category, is_public, equipment, level, force, mechanic, instructions, primary_muscles, secondary_muscles, coaching_cues, common_mistakes)
VALUES ('Underhand Cable Pulldowns', 'cable', true, 'cable', 'beginner', 'pull', 'compound', ARRAY['Sit down on a pull-down machine with a wide bar attached to the top pulley. Adjust the knee pad of the machine to fit your height. These pads will prevent your body from being raised by the resistance attached to the bar.','Grab the pull-down bar with the palms facing your torso (a supinated grip). Make sure that the hands are placed closer than the shoulder width.','As you have both arms extended in front of you holding the bar at the chosen grip width, bring your torso back around 30 degrees or so while creating a curvature on your lower back and sticking your chest out. This is your starting position.','As you breathe out, pull the bar down until it touches your upper chest by drawing the shoulders and the upper arms down and back. Tip: Concentrate on squeezing the back muscles once you reach the fully contracted position and keep the elbows close to your body. The upper torso should remain stationary as your bring the bar to you and only the arms should move. The forearms should do no other work other than hold the bar.','After a second on the contracted position, while breathing in, slowly bring the bar back to the starting position when your arms are fully extended and the lats are fully stretched.','Repeat this motion for the prescribed amount of repetitions.'], ARRAY['lats'], ARRAY['biceps','middle back','shoulders'], ARRAY[]::TEXT[], ARRAY[]::TEXT[])
ON CONFLICT DO NOTHING;

INSERT INTO exercises (name, category, is_public, equipment, level, force, mechanic, instructions, primary_muscles, secondary_muscles, coaching_cues, common_mistakes)
VALUES ('Upright Barbell Row', 'barbell', true, 'barbell', 'beginner', 'pull', 'compound', ARRAY['Grasp a barbell with an overhand grip that is slightly less than shoulder width. The bar should be resting on the top of your thighs with your arms extended and a slight bend in your elbows. Your back should also be straight. This will be your starting position.','Now exhale and use the sides of your shoulders to lift the bar, raising your elbows up and to the side. Keep the bar close to your body as you raise it. Continue to lift the bar until it nearly touches your chin. Tip: Your elbows should drive the motion, and should always be higher than your forearms. Remember to keep your torso stationary and pause for a second at the top of the movement.','Lower the bar back down slowly to the starting position. Inhale as you perform this portion of the movement.','Repeat for the recommended amount of repetitions.'], ARRAY['shoulders'], ARRAY['traps'], ARRAY[]::TEXT[], ARRAY[]::TEXT[])
ON CONFLICT DO NOTHING;

INSERT INTO exercises (name, category, is_public, equipment, level, force, mechanic, instructions, primary_muscles, secondary_muscles, coaching_cues, common_mistakes)
VALUES ('Upright Cable Row', 'cable', true, 'cable', 'intermediate', 'pull', 'compound', ARRAY['Grasp a straight bar cable attachment that is attached to a low pulley with a pronated (palms facing your thighs) grip that is slightly less than shoulder width. The bar should be resting on top of your thighs. Your arms should be extended with a slight bend at the elbows and your back should be straight. This will be your starting position.','Use your side shoulders to lift the cable bar as you exhale. The bar should be close to the body as you move it up. Continue to lift it until it nearly touches your chin. Tip: Your elbows should drive the motion. As you lift the bar, your elbows should always be higher than your forearms. Also, keep your torso stationary and pause for a second at the top of the movement.','Lower the bar back down slowly to the starting position. Inhale as you perform this portion of the movement.','Repeat for the recommended amount of repetitions.'], ARRAY['traps'], ARRAY['shoulders'], ARRAY[]::TEXT[], ARRAY[]::TEXT[])
ON CONFLICT DO NOTHING;

INSERT INTO exercises (name, category, is_public, equipment, level, force, mechanic, instructions, primary_muscles, secondary_muscles, coaching_cues, common_mistakes)
VALUES ('Upright Row - With Bands', 'bands', true, 'bands', 'beginner', 'pull', 'compound', ARRAY['To begin, stand on an exercise band so that tension begins at arm''s length. Grasp the handles using a pronated (palms facing your thighs) grip that is slightly less than shoulder width. The handles should be resting on top of your thighs. Your arms should be extended with a slight bend at the elbows and your back should be straight. This will be your starting position.','Use your side shoulders to lift the handles as you exhale. The handles should be close to the body as you move them up. Continue to lift the handles until they nearly touches your chin. Tip: Your elbows should drive the motion. As you lift the handles, your elbows should always be higher than your forearms. Also, keep your torso stationary and pause for a second at the top of the movement.','Lower the handles back down slowly to the starting position. Inhale as you perform this portion of the movement.','Repeat for the recommended amount of repetitions.'], ARRAY['traps'], ARRAY['shoulders'], ARRAY[]::TEXT[], ARRAY[]::TEXT[])
ON CONFLICT DO NOTHING;

INSERT INTO exercises (name, category, is_public, equipment, level, force, mechanic, instructions, primary_muscles, secondary_muscles, coaching_cues, common_mistakes)
VALUES ('V-Bar Pulldown', 'cable', true, 'cable', 'intermediate', 'pull', 'compound', ARRAY['Sit down on a pull-down machine with a V-Bar attached to the top pulley.','Adjust the knee pad of the machine to fit your height. These pads will prevent your body from being raised by the resistance attached to the bar.','Grab the V-bar with the palms facing each other (a neutral grip). Stick your chest out and lean yourself back slightly (around 30-degrees) in order to better engage the lats. This will be your starting position.','Using your lats, pull the bar down as you squeeze your shoulder blades. Continue until your chest nearly touches the V-bar. Exhale as you execute this motion. Tip: Keep the torso stationary throughout the movement.','After a second hold on the contracted position, slowly bring the bar back to the starting position as you breathe in.','Repeat for the prescribed number of repetitions.'], ARRAY['lats'], ARRAY['biceps','middle back','shoulders'], ARRAY[]::TEXT[], ARRAY[]::TEXT[])
ON CONFLICT DO NOTHING;

INSERT INTO exercises (name, category, is_public, equipment, level, force, mechanic, instructions, primary_muscles, secondary_muscles, coaching_cues, common_mistakes)
VALUES ('V-Bar Pullup', 'body only', true, 'body only', 'beginner', 'pull', 'compound', ARRAY['Start by placing the middle of the V-bar in the middle of the pull-up bar (assuming that the pull-up station you are using does not have neutral grip handles). The V-Bar handles will be facing down so that you can hang from the pull-up bar through the use of the handles.','Once you securely place the V-bar, take a hold of the bar from each side and hang from it. Stick your chest out and lean yourself back slightly in order to better engage the lats. This will be your starting position.','Using your lats, pull your torso up while leaning your head back slightly so that you do not hit yourself with the chin-up bar. Continue until your chest nearly touches the V-bar. Exhale as you execute this motion.','After a second hold on the contracted position, slowly lower your body back to the starting position as you breathe in.','Repeat for the prescribed number of repetitions.'], ARRAY['lats'], ARRAY['biceps','middle back','shoulders'], ARRAY[]::TEXT[], ARRAY[]::TEXT[])
ON CONFLICT DO NOTHING;

INSERT INTO exercises (name, category, is_public, equipment, level, force, mechanic, instructions, primary_muscles, secondary_muscles, coaching_cues, common_mistakes)
VALUES ('Vertical Swing', 'dumbbell', true, 'dumbbell', 'beginner', 'pull', 'compound', ARRAY['Allow the dumbbell to hang at arms length between your legs, holding it with both hands. Keep your back straight and your head up.','Swing the dumbbell between your legs, flexing at the hips and bending the knees slightly.','Powerfully reverse the motion by extending at the hips, knees, and ankles to propel yourself upward, swinging the dumbell over your head.','As you land, absorb the impact through your legs and draw the dumbbell to your torso before the next repetition.'], ARRAY['hamstrings'], ARRAY['glutes','quadriceps','shoulders'], ARRAY[]::TEXT[], ARRAY[]::TEXT[])
ON CONFLICT DO NOTHING;

INSERT INTO exercises (name, category, is_public, equipment, level, force, mechanic, instructions, primary_muscles, secondary_muscles, coaching_cues, common_mistakes)
VALUES ('Walking, Treadmill', 'machine', true, 'machine', 'beginner', NULL, NULL, ARRAY['To begin, step onto the treadmill and select the desired option from the menu. Most treadmills have a manual setting, or you can select a program to run. Typically, you can enter your age and weight to estimate the amount of calories burned during exercise. Elevation can be adjusted to change the intensity of the workout.','Treadmills offer convenience, cardiovascular benefits, and usually have less impact than walking outside. When walking, you should move at a moderate to fast pace, not a leisurely one. Being an activity of lower intensity, walking doesn''t burn as many calories as some other activities, but still provides great benefit. A 150 lb person will burn about 175 calories walking 4 miles per hour for 30 minutes, compared to 450 calories running twice as fast. Maintain proper posture as you walk, and only hold onto the handles when necessary, such as when dismounting or checking your heart rate.'], ARRAY['quadriceps'], ARRAY['calves','glutes','hamstrings'], ARRAY[]::TEXT[], ARRAY[]::TEXT[])
ON CONFLICT DO NOTHING;

INSERT INTO exercises (name, category, is_public, equipment, level, force, mechanic, instructions, primary_muscles, secondary_muscles, coaching_cues, common_mistakes)
VALUES ('Weighted Ball Hyperextension', 'exercise ball', true, 'exercise ball', 'intermediate', 'pull', 'compound', ARRAY['To begin, lie down on an exercise ball with your torso pressing against the ball and parallel to the floor. The ball of your feet should be pressed against the floor to help keep you balanced. Place a weighted plate under your chin or behind your neck. This is the starting position.','Slowly raise your torso up by bending at the waist and lower back. Remember to exhale during this movement.','Hold the contraction on your lower back for a second and lower your torso back down to the starting position while inhaling.','Repeat for the recommended amount of repetitions prescribed in your program.'], ARRAY['lower back'], ARRAY['glutes','hamstrings','middle back'], ARRAY[]::TEXT[], ARRAY[]::TEXT[])
ON CONFLICT DO NOTHING;

INSERT INTO exercises (name, category, is_public, equipment, level, force, mechanic, instructions, primary_muscles, secondary_muscles, coaching_cues, common_mistakes)
VALUES ('Weighted Ball Side Bend', 'exercise ball', true, 'exercise ball', 'intermediate', 'pull', 'isolation', ARRAY['To begin, lie down on an exercise ball with your left side of the torso (waist, hips and shoulder) pressed against the ball.','Your feet should be on the floor while your legs are crossed and hanging from the ball. Hold a weighted plate with your right hand directly to the right side of your head. Tip: Make sure the smooth side of the plate is resting against your head.','Place your left arm across your torso so that your palm is on your obliques. There should be a right angle between your left forearm and upper arm. This is the starting position.','Raise the side of your torso up by laterally flexing at the waist while exhaling.','Hold the contraction for a second and slowly lower yourself back down to the starting position while inhaling.','Repeat for the recommended amount of repetitions.','Switch sides and repeat the exercise.'], ARRAY['abdominals'], ARRAY[]::TEXT[], ARRAY[]::TEXT[], ARRAY[]::TEXT[])
ON CONFLICT DO NOTHING;

INSERT INTO exercises (name, category, is_public, equipment, level, force, mechanic, instructions, primary_muscles, secondary_muscles, coaching_cues, common_mistakes)
VALUES ('Weighted Bench Dip', 'other', true, 'other', 'intermediate', 'push', 'compound', ARRAY['For this exercise you will need to place a bench behind your back and another one in front of you. With the benches perpendicular to your body, hold on to one bench on its edge with the hands close to your body, separated at shoulder width. Your arms should be fully extended.','The legs will be extended forward on top of the other bench. Your legs should be parallel to the floor while your torso is to be perpendicular to the floor. Have your partner place the dumbbell on your lap. Note: This exercise is best performed with a partner as placing the weight on your lap can be challenging and cause injury without assistance. This will be your starting position.','Slowly lower your body as you inhale by bending at the elbows until you lower yourself far enough to where there is an angle slightly smaller than 90 degrees between the upper arm and the forearm. Tip: Keep the elbows as close as possible throughout the movement. Forearms should always be pointing down.','Using your triceps to bring your torso up again, lift yourself back to the starting position while exhaling.','Repeat for the recommended amount of repetitions.'], ARRAY['triceps'], ARRAY['chest','shoulders'], ARRAY[]::TEXT[], ARRAY[]::TEXT[])
ON CONFLICT DO NOTHING;

INSERT INTO exercises (name, category, is_public, equipment, level, force, mechanic, instructions, primary_muscles, secondary_muscles, coaching_cues, common_mistakes)
VALUES ('Weighted Crunches', 'medicine ball', true, 'medicine ball', 'beginner', 'pull', 'isolation', ARRAY['Lie flat on your back with your feet flat on the ground or resting on a bench with your knees bent at a 90 degree angle.','Hold a weight to your chest, or you may hold it extended above your torso. This will be your starting position.','Now, exhale and slowly begin to roll your shoulders off the floor. Your shoulders should come up off the floor about 4 inches while your lower back remains on the floor.','At the top of the movement, flex your abdominals and hold for a brief pause.','Then inhale and slowly lower yourself back down to the starting position.'], ARRAY['abdominals'], ARRAY[]::TEXT[], ARRAY[]::TEXT[], ARRAY[]::TEXT[])
ON CONFLICT DO NOTHING;

INSERT INTO exercises (name, category, is_public, equipment, level, force, mechanic, instructions, primary_muscles, secondary_muscles, coaching_cues, common_mistakes)
VALUES ('Weighted Jump Squat', 'barbell', true, 'barbell', 'intermediate', 'push', 'compound', ARRAY['Position a lightly loaded barbell across the back of your shoulders. You could also use a weighted vest, sandbag, or other type of resistance for this exercise.','The weight should be light enough that it doesn''t slow you down significantly. Your feet should be just outside of shoulder width with your head and chest up. This will be your starting position.','Using a countermovement, squat partially down and immediately reverse your direction to explode off of the ground, extending through your hips, knees, and ankles. Maintain good posture throughout the jump.','As you return to the ground, absorb the impact through your legs.'], ARRAY['quadriceps'], ARRAY['calves','glutes','hamstrings','lower back'], ARRAY[]::TEXT[], ARRAY[]::TEXT[])
ON CONFLICT DO NOTHING;

INSERT INTO exercises (name, category, is_public, equipment, level, force, mechanic, instructions, primary_muscles, secondary_muscles, coaching_cues, common_mistakes)
VALUES ('Weighted Pull Ups', 'other', true, 'other', 'intermediate', 'pull', 'compound', ARRAY['Attach a weight to a dip belt and secure it around your waist. Grab the pull-up bar with the palms of your hands facing forward. For a medium grip, your hands should be spaced at shoulder width. Both arms should be extended in front of you holding the bar at the chosen grip.','You''ll want to bring your torso back about 30 degrees while creating a curvature in your lower back and sticking your chest out. This will be your starting position.','Now, exhale and pull your torso up until your head is above your hands. Concentrate on squeezing yourshoulder blades back and down as you reach the top contracted position.','After a brief moment at the top contracted position, inhale and slowly lower your torso back to the starting position with your arms extended and your lats fully stretched.'], ARRAY['lats'], ARRAY['biceps','middle back'], ARRAY[]::TEXT[], ARRAY[]::TEXT[])
ON CONFLICT DO NOTHING;

INSERT INTO exercises (name, category, is_public, equipment, level, force, mechanic, instructions, primary_muscles, secondary_muscles, coaching_cues, common_mistakes)
VALUES ('Weighted Sissy Squat', 'barbell', true, 'barbell', 'expert', 'push', 'compound', ARRAY['Standing upright, with feet at shoulder width and toes raised, use one hand to hold onto the beams of a squat rack and the opposite arm to hold a plate on top of your chest. This is your starting position.','As you use one arm to hold yourself, bend at the knees and slowly lower your torso toward the ground by bringing your pelvis and knees forward. Inhale as you go down and stop when your upper and lower legs almost create a 90-degree angle. Hold the stretch position for a second.','After your one second hold, use your thigh muscles to bring your torso back up to the starting position. Exhale as you move up.','Repeat for the recommended amount of times.'], ARRAY['quadriceps'], ARRAY['calves','glutes','hamstrings'], ARRAY[]::TEXT[], ARRAY[]::TEXT[])
ON CONFLICT DO NOTHING;

INSERT INTO exercises (name, category, is_public, equipment, level, force, mechanic, instructions, primary_muscles, secondary_muscles, coaching_cues, common_mistakes)
VALUES ('Weighted Sit-Ups - With Bands', 'other', true, 'other', 'intermediate', 'pull', 'isolation', ARRAY['Start out by strapping the bands around the base of the decline bench. Place the handles towards the inside of the decline bench so that when lying down, you can reach for both of them.','Position your legs through the decline machine until they are secured. Now reach for the exercise bands with both hands. Use a pronated (palms forward) grip to grasp the handles. Position them near your collar bone and rotate your wrist to a neutral grip (palms facing the torso). Note: Your arms should remain stationary throughout the exercise. This is the starting position.','Move your torso upward until your upper body is perpendicular to the floor while exhaling. Hold the contraction for a second and lower your upper body back down to the starting position while inhaling.','Repeat for the recommended amount of repetitions.'], ARRAY['abdominals'], ARRAY[]::TEXT[], ARRAY[]::TEXT[], ARRAY[]::TEXT[])
ON CONFLICT DO NOTHING;

INSERT INTO exercises (name, category, is_public, equipment, level, force, mechanic, instructions, primary_muscles, secondary_muscles, coaching_cues, common_mistakes)
VALUES ('Weighted Squat', 'other', true, 'other', 'intermediate', 'push', 'compound', ARRAY['Start by positioning two flat benches shoulder width apart from each other. Stand on top of them and wrap the weighted belt around your waist with the amount of weight you feel comfortable with. Make sure your toes are facing out.','Once you are standing straight up with the weight hanging in between your legs, position your arms so that they are fully extended to the side of your body. This is the starting position.','Begin by bending the knees as you maintain a straight posture with the head up. Continue down until the angle between the upper leg and the calves becomes slightly less than 90-degrees (which is the point in which the upper legs are below parallel to the floor). Inhale as you perform this portion of the movement. Tip: If you performed the exercise correctly, the front of the knees should make an imaginary straight line with the toes that are perpendicular to the front. If your knees are past that imaginary line (if they are past your toes) then you are placing undue stress on the knee and the exercise has been performed incorrectly.','Begin to move the body back up by pushing the floor of the flat bench with the ball of your foot mainly as you straighten the legs again and go back to the starting position. Exhale as you perform this portion of the exercise.','Repeat for the recommended amount of repetitions.'], ARRAY['quadriceps'], ARRAY['calves','glutes','hamstrings'], ARRAY[]::TEXT[], ARRAY[]::TEXT[])
ON CONFLICT DO NOTHING;

INSERT INTO exercises (name, category, is_public, equipment, level, force, mechanic, instructions, primary_muscles, secondary_muscles, coaching_cues, common_mistakes)
VALUES ('Wide-Grip Barbell Bench Press', 'barbell', true, 'barbell', 'intermediate', 'push', 'compound', ARRAY['Lie back on a flat bench with feet firm on the floor. Using a wide, pronated (palms forward) grip that is around 3 inches away from shoulder width (for each hand), lift the bar from the rack and hold it straight over you with your arms locked. The bar will be perpendicular to the torso and the floor. This will be your starting position.','As you breathe in, come down slowly until you feel the bar on your middle chest.','After a second pause, bring the bar back to the starting position as you breathe out and push the bar using your chest muscles. Lock your arms and squeeze your chest in the contracted position, hold for a second and then start coming down slowly again. Tip: It should take at least twice as long to go down than to come up.','Repeat the movement for the prescribed amount of repetitions.'], ARRAY['chest'], ARRAY['shoulders','triceps'], ARRAY[]::TEXT[], ARRAY[]::TEXT[])
ON CONFLICT DO NOTHING;

INSERT INTO exercises (name, category, is_public, equipment, level, force, mechanic, instructions, primary_muscles, secondary_muscles, coaching_cues, common_mistakes)
VALUES ('Wide-Grip Decline Barbell Bench Press', 'barbell', true, 'barbell', 'intermediate', 'push', 'compound', ARRAY['Lie back on a decline bench with the feet securely locked at the front of the bench. Using a wide, pronated (palms forward) grip that is around 3 inches away from shoulder width (for each hand), lift the bar from the rack and hold it straight over you with your arms locked. The bar will be perpendicular to the torso and the floor. This will be your starting position.','As you breathe in, come down slowly until you feel the bar on your lower chest.','After a second pause, bring the bar back to the starting position as you breathe out and push the bar using your chest muscles. Lock your arms and squeeze your chest in the contracted position, hold for a second and then start coming down slowly again. Tip: It should take at least twice as long to go down than to come up.','Repeat the movement for the prescribed amount of repetitions.'], ARRAY['chest'], ARRAY['shoulders','triceps'], ARRAY[]::TEXT[], ARRAY[]::TEXT[])
ON CONFLICT DO NOTHING;

INSERT INTO exercises (name, category, is_public, equipment, level, force, mechanic, instructions, primary_muscles, secondary_muscles, coaching_cues, common_mistakes)
VALUES ('Wide-Grip Decline Barbell Pullover', 'barbell', true, 'barbell', 'intermediate', 'pull', 'compound', ARRAY['Lie down on a decline bench with both legs securely locked in position. Reach for the barbell behind the head using a pronated grip (palms facing out). Make sure to grab the barbell wider than shoulder width apart for this exercise. Slowly lift the barbell up from the floor by using your arms.','When positioned properly, your arms should be fully extended and perpendicular to the floor. This is the starting position.','Begin by moving the barbell back down in a semicircular motion as if you were going to place it on the floor, but instead, stop when the arms are parallel to the floor. Tip: Keep the arms fully extended at all times. The movement should only happen at the shoulder joint. Inhale as you perform this portion of the movement.','Now bring the barbell up while exhaling until you are back at the starting position. Remember to keep full control of the barbell at all times.','Repeat the movement for the prescribed amount of repetitions of your training program.','When finished with your set, slowly lower the barbell back down until it is level with your head and release it.'], ARRAY['chest'], ARRAY['shoulders','triceps'], ARRAY[]::TEXT[], ARRAY[]::TEXT[])
ON CONFLICT DO NOTHING;

INSERT INTO exercises (name, category, is_public, equipment, level, force, mechanic, instructions, primary_muscles, secondary_muscles, coaching_cues, common_mistakes)
VALUES ('Wide-Grip Lat Pulldown', 'cable', true, 'cable', 'beginner', 'pull', 'compound', ARRAY['Sit down on a pull-down machine with a wide bar attached to the top pulley. Make sure that you adjust the knee pad of the machine to fit your height. These pads will prevent your body from being raised by the resistance attached to the bar.','Grab the bar with the palms facing forward using the prescribed grip. Note on grips: For a wide grip, your hands need to be spaced out at a distance wider than shoulder width. For a medium grip, your hands need to be spaced out at a distance equal to your shoulder width and for a close grip at a distance smaller than your shoulder width.','As you have both arms extended in front of you holding the bar at the chosen grip width, bring your torso back around 30 degrees or so while creating a curvature on your lower back and sticking your chest out. This is your starting position.','As you breathe out, bring the bar down until it touches your upper chest by drawing the shoulders and the upper arms down and back. Tip: Concentrate on squeezing the back muscles once you reach the full contracted position. The upper torso should remain stationary and only the arms should move. The forearms should do no other work except for holding the bar; therefore do not try to pull down the bar using the forearms.','After a second at the contracted position squeezing your shoulder blades together, slowly raise the bar back to the starting position when your arms are fully extended and the lats are fully stretched. Inhale during this portion of the movement.','Repeat this motion for the prescribed amount of repetitions.'], ARRAY['lats'], ARRAY['biceps','middle back','shoulders'], ARRAY['Grip outside shoulder width','Pull bar to upper chest, lean back slightly','Drive elbows down and back','Control the return all the way up','Feel lats stretch at top'], ARRAY['Pulling behind the neck','Leaning too far back','Using body momentum','Grip too narrow'])
ON CONFLICT DO NOTHING;

INSERT INTO exercises (name, category, is_public, equipment, level, force, mechanic, instructions, primary_muscles, secondary_muscles, coaching_cues, common_mistakes)
VALUES ('Wide-Grip Pulldown Behind The Neck', 'cable', true, 'cable', 'intermediate', 'pull', 'compound', ARRAY['Sit down on a pull-down machine with a wide bar attached to the top pulley. Make sure that you adjust the knee pad of the machine to fit your height. These pads will prevent your body from being raised by the resistance attached to the bar.','Grab the bar with the palms facing forward using the prescribed grip. Note on grips: For a wide grip, your hands need to be spaced out at a distance wider than your shoulder width. For a medium grip, your hands need to be spaced out at a distance equal to your shoulder width and for a close grip at a distance smaller than your shoulder width.','As you have both arms extended in front of you holding the bar at the chosen grip width, bring your torso and head forward. Think of an imaginary line from the center of the bar down to the back of your neck. This is your starting position.','As you breathe out, bring the bar down until it touches the back of your neck by drawing the shoulders and the upper arms down and back. Tip: Concentrate on squeezing the back muscles once you reach the full contracted position. The upper torso should remain stationary and only the arms should move. The forearms should do no other work except for holding the bar; therefore do not try to pull down the bar using the forearms.','After a second on the contracted position squeezing your shoulder blades together, slowly raise the bar back to the starting position when your arms are fully extended and the lats are fully stretched. Inhale during this portion of the movement.','Repeat this motion for the prescribed amount of repetitions.'], ARRAY['lats'], ARRAY['biceps','middle back','shoulders'], ARRAY[]::TEXT[], ARRAY[]::TEXT[])
ON CONFLICT DO NOTHING;

INSERT INTO exercises (name, category, is_public, equipment, level, force, mechanic, instructions, primary_muscles, secondary_muscles, coaching_cues, common_mistakes)
VALUES ('Wide-Grip Rear Pull-Up', 'body only', true, 'body only', 'intermediate', 'pull', 'compound', ARRAY['Grab the pull-up bar with the palms facing forward using a wide grip.','As you have both arms extended in front of you holding the bar, bring your torso forward and head so that there is an imaginary line from the pull-up bar to the back of your neck. This is your starting position.','Pull your torso up until the bar is near the back of your neck. To do this, draw the shoulders and upper arms down and back while slightly leaning your head forward. Exhale as you perform this portion of the movement. Tip: Concentrate on squeezing the back muscles once you reach the full contracted position. The upper torso should remain stationary as it moves through space and only the arms should move. The forearms should do no other work other than hold the bar.','After a second on the contracted position, start to inhale and slowly lower your torso back to the starting position when your arms are fully extended and the lats are fully stretched.','Repeat this motion for the prescribed amount of repetitions.'], ARRAY['lats'], ARRAY['biceps','middle back','shoulders'], ARRAY[]::TEXT[], ARRAY[]::TEXT[])
ON CONFLICT DO NOTHING;

INSERT INTO exercises (name, category, is_public, equipment, level, force, mechanic, instructions, primary_muscles, secondary_muscles, coaching_cues, common_mistakes)
VALUES ('Wide-Grip Standing Barbell Curl', 'barbell', true, 'barbell', 'beginner', 'pull', 'isolation', ARRAY['Stand up with your torso upright while holding a barbell at the wide outer handle. The palm of your hands should be facing forward. The elbows should be close to the torso. This will be your starting position.','While holding the upper arms stationary, curl the weights forward while contracting the biceps as you breathe out. Tip: Only the forearms should move.','Continue the movement until your biceps are fully contracted and the bar is at shoulder level. Hold the contracted position for a second and squeeze the biceps hard.','Slowly begin to bring the bar back to starting position as your breathe in.','Repeat for the recommended amount of repetitions.'], ARRAY['biceps'], ARRAY[]::TEXT[], ARRAY[]::TEXT[], ARRAY[]::TEXT[])
ON CONFLICT DO NOTHING;

INSERT INTO exercises (name, category, is_public, equipment, level, force, mechanic, instructions, primary_muscles, secondary_muscles, coaching_cues, common_mistakes)
VALUES ('Wide Stance Barbell Squat', 'barbell', true, 'barbell', 'intermediate', 'push', 'compound', ARRAY['This exercise is best performed inside a squat rack for safety purposes. To begin, first set the bar on a rack that best matches your height. Once the correct height is chosen and the bar is loaded, step under the bar and place the back of your shoulders (slightly below the neck) across it.','Hold on to the bar using both arms at each side and lift it off the rack by first pushing with your legs and at the same time straightening your torso.','Step away from the rack and position your legs using a wider-than-shoulder-width stance with the toes slightly pointed out. Keep your head up at all times as looking down will get you off balance, and also maintain a straight back. This will be your starting position.','Begin to slowly lower the bar by bending the knees as you maintain a straight posture with the head up. Continue down until the angle between the upper leg and the calves becomes slightly less than 90-degrees (which is the point in which the upper legs are below parallel to the floor). Inhale as you perform this portion of the movement. Tip: If you performed the exercise correctly, the front of the knees should make an imaginary straight line with the toes that is perpendicular to the front. If your knees are past that imaginary line (if they are past your toes) then you are placing undue stress on the knee and the exercise has been performed incorrectly.','Begin to raise the bar as you exhale by pushing the floor with the heel of your foot as you straighten the legs again and go back to the starting position.','Repeat for the recommended amount of repetitions.'], ARRAY['quadriceps'], ARRAY['calves','glutes','hamstrings','lower back'], ARRAY[]::TEXT[], ARRAY[]::TEXT[])
ON CONFLICT DO NOTHING;

INSERT INTO exercises (name, category, is_public, equipment, level, force, mechanic, instructions, primary_muscles, secondary_muscles, coaching_cues, common_mistakes)
VALUES ('Wide Stance Stiff Legs', 'barbell', true, 'barbell', 'intermediate', 'pull', 'compound', ARRAY['Begin with a barbell loaded on the floor. Adopt a wide stance, and then bend at the hips to grab the bar. Your hips should be as far back as possible, and your legs nearly straight. Keep your back straight, and your head and chest up. This will be your starting position.','Begin the movement be engaging the hips, driving them forward as you allow the arms to hang straight. Continue until you are standing straight up, and then slowly return the weight to the starting position. For successive reps, the weight need not touch the floor.'], ARRAY['hamstrings'], ARRAY['adductors','glutes','lower back'], ARRAY[]::TEXT[], ARRAY[]::TEXT[])
ON CONFLICT DO NOTHING;

INSERT INTO exercises (name, category, is_public, equipment, level, force, mechanic, instructions, primary_muscles, secondary_muscles, coaching_cues, common_mistakes)
VALUES ('Wind Sprints', 'body only', true, 'body only', 'beginner', 'pull', 'compound', ARRAY['Hang from a pull-up bar using a pronated grip. Your arms and legs should be extended. This will be your starting position.','Begin by quickly raising one knee as high as you can. Do not swing your body or your legs. 3','Immediately reverse the motion, returning that leg to the starting position. Simultaneously raise the opposite knee as high as possible.','Continue alternating between legs until the set is complete.'], ARRAY['abdominals'], ARRAY[]::TEXT[], ARRAY[]::TEXT[], ARRAY[]::TEXT[])
ON CONFLICT DO NOTHING;

INSERT INTO exercises (name, category, is_public, equipment, level, force, mechanic, instructions, primary_muscles, secondary_muscles, coaching_cues, common_mistakes)
VALUES ('Wrist Roller', 'other', true, 'other', 'beginner', 'pull', 'isolation', ARRAY['To begin, stand straight up grabbing a wrist roller using a pronated grip (palms facing down). Your feet should be shoulder width apart.','Slowly lift both arms until they are fully extended and parallel to the floor in front of you. Note: Make sure the rope is not wrapped around the roller. Your entire body should be stationary except for the forearms. This is the starting position.','Rotate one wrist at a time in an upward motion to bring the weight up to the bar by rolling the rope around the roller.','Once the weight has reached the bar, slowly begin to lower the weight back down by rotating the wrist in a downward motion until the weight reaches the starting position.','Repeat for the prescribed amount of repetitions in your program.'], ARRAY['forearms'], ARRAY['shoulders'], ARRAY[]::TEXT[], ARRAY[]::TEXT[])
ON CONFLICT DO NOTHING;

INSERT INTO exercises (name, category, is_public, equipment, level, force, mechanic, instructions, primary_muscles, secondary_muscles, coaching_cues, common_mistakes)
VALUES ('Wrist Rotations with Straight Bar', 'barbell', true, 'barbell', 'beginner', 'pull', 'isolation', ARRAY['Hold a barbell with both hands and your palms facing down; hands spaced about shoulder width. This will be your starting position.','Alternating between each of your hands, perform the movement by extending the wrist as though you were rolling up a newspaper. Continue alternating back and forth until failure.','Reverse the motion by flexing the wrist, rolling the opposite direction. Continue the alternating motion until failure.'], ARRAY['forearms'], ARRAY[]::TEXT[], ARRAY[]::TEXT[], ARRAY[]::TEXT[])
ON CONFLICT DO NOTHING;

INSERT INTO exercises (name, category, is_public, equipment, level, force, mechanic, instructions, primary_muscles, secondary_muscles, coaching_cues, common_mistakes)
VALUES ('Yoke Walk', 'other', true, 'other', 'intermediate', NULL, 'compound', ARRAY['The yoke is usually done with a yoke apparatus, but is sometimes seen with refrigerators or other heavy objects.','Begin by racking the apparatus across the back of the shoulders. With your head looking forward and back arched, lift the yoke by driving through the heels.','Begin walking as quickly as possible using short, quick steps. You may hold the side posts of the yoke to help steady it and hold it in position. Continue for the given distance as fast as possible, usually 75-100 feet.'], ARRAY['quadriceps'], ARRAY['abdominals','abductors','adductors','calves','glutes','hamstrings','lower back'], ARRAY[]::TEXT[], ARRAY[]::TEXT[])
ON CONFLICT DO NOTHING;

INSERT INTO exercises (name, category, is_public, equipment, level, force, mechanic, instructions, primary_muscles, secondary_muscles, coaching_cues, common_mistakes)
VALUES ('Zercher Squats', 'barbell', true, 'barbell', 'expert', 'push', 'compound', ARRAY['This exercise is best performed inside a squat rack for safety purposes. To begin, first set the bar on a rack that best matches your height. The correct height should be anywhere above the waist but below the chest. Once the correct height is chosen and the bar is loaded, lock your hands together and place the bar on top of your arms in between the forearm and upper arm.','Lift the bar up so that it is resting on top of your forearms. If you are holding the bar properly, it should look as if you have your arms crossed but with a bar running across them.','Step away from the rack and position your legs using a shoulder width medium stance with the toes slightly pointed out. Keep your head up at all times as looking down will get you off balance and also maintain a straight back. This will be your starting position. (Note: For the purposes of this discussion we will use the medium stance described above which targets overall development; however you can choose any of the three stances discussed in the foot stances section).','Begin to lower the bar by bending the knees as you maintain a straight posture with the head up. Continue down until the angle between the upper leg and the calves becomes slightly less than 90-degrees (which is the point in which the upper legs are below parallel to the floor). Inhale as you perform this portion of the movement. Tip: If you performed the exercise correctly, the front of the knees should make an imaginary straight line with the toes that is perpendicular to the front. If your knees are past that imaginary line (if they are past your toes) then you are placing undue stress on the knee and the exercise has been performed incorrectly.','Begin to raise the bar as you exhale by pushing the floor with the ball of your foot mainly as you straighten the legs again and go back to the starting position.','Repeat for the recommended amount of repetitions.'], ARRAY['quadriceps'], ARRAY['calves','glutes','hamstrings'], ARRAY[]::TEXT[], ARRAY[]::TEXT[])
ON CONFLICT DO NOTHING;

INSERT INTO exercises (name, category, is_public, equipment, level, force, mechanic, instructions, primary_muscles, secondary_muscles, coaching_cues, common_mistakes)
VALUES ('Zottman Curl', 'dumbbell', true, 'dumbbell', 'intermediate', 'pull', 'isolation', ARRAY['Stand up with your torso upright and a dumbbell in each hand being held at arms length. The elbows should be close to the torso.','Make sure the palms of the hands are facing each other. This will be your starting position.','While holding the upper arm stationary, curl the weights while contracting the biceps as you breathe out. Only the forearms should move. Your wrist should rotate so that you have a supinated (palms up) grip. Continue the movement until your biceps are fully contracted and the dumbbells are at shoulder level.','Hold the contracted position for a second as you squeeze the biceps.','Now during the contracted position, rotate your wrist until you now have a pronated (palms facing down) grip with the thumb at a higher position than the pinky.','Slowly begin to bring the dumbbells back down using the pronated grip.','As the dumbbells close your thighs, start rotating the wrist so that you go back to a neutral (palms facing your body) grip.','Repeat for the recommended amount of repetitions.'], ARRAY['biceps'], ARRAY['forearms'], ARRAY[]::TEXT[], ARRAY[]::TEXT[])
ON CONFLICT DO NOTHING;

INSERT INTO exercises (name, category, is_public, equipment, level, force, mechanic, instructions, primary_muscles, secondary_muscles, coaching_cues, common_mistakes)
VALUES ('Zottman Preacher Curl', 'dumbbell', true, 'dumbbell', 'intermediate', 'pull', 'isolation', ARRAY['Grab a dumbbell in each hand and place your upper arms on top of the preacher bench or the incline bench. The dumbbells should be held at shoulder height and the elbows should be flexed. Hold the dumbbells with the palms of your hands facing down. This will be your starting position.','As you breathe in, slowly lower the dumbbells keeping the palms down until your upper arm is extended and your biceps are fully stretched.','Now rotate your wrists once you are at the bottom of the movement so that the palms of the hands are facing up.','As you exhale, use your biceps to curl the weights up until they are fully contracted and the dumbbells are at shoulder height. Again, remember that to ensure full contraction you need to bring that small finger higher than the thumb.','Squeeze the biceps hard for a second at the contracted position and rotate your wrists so that the palms are facing down again.','Repeat for the recommended amount of repetitions.'], ARRAY['biceps'], ARRAY['forearms'], ARRAY[]::TEXT[], ARRAY[]::TEXT[])
ON CONFLICT DO NOTHING;

