/**
 * Exercise Library - 155+ exercises with full metadata for the workout generator
 * 
 * IMPORTANT: Exercise names MUST match lib/exercises.ts exactly for backward
 * compatibility with PR tracking (which uses exercise_name text field).
 * 
 * Exercises are organized by movement pattern for easy browsing.
 */

import type { Exercise } from '../generator/types';

// =============================================================================
// HORIZONTAL PUSH - Bench press variations, push-ups
// =============================================================================

const horizontalPush: Exercise[] = [
  {
    id: 'bench-press',
    name: 'Bench Press',
    category: 'compound',
    movementPattern: 'horizontal_push',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['front_delts', 'triceps'],
    equipment: ['barbell', 'bench', 'squat_rack'],
    difficulty: 'intermediate',
    jointStress: { shoulder: 'moderate', elbow: 'low' },
    defaultRestSeconds: 180,
    repRangeMin: 3,
    repRangeMax: 12,
    canBeSuperset: false,
    isUnilateral: false,
    youtubeVideoId: 'rTy5TsIj2sU',
    videoStartTime: 0,
    videoEndTime: 35,
    similarExercises: ['dumbbell-bench-press', 'machine-chest-press'],
    easierVariation: 'push-up',
    harderVariation: 'paused-bench-press',
    requiresSpotter: true,
    highFatigueImpact: true,
  },
  {
    id: 'incline-bench-press',
    name: 'Incline Bench Press',
    category: 'compound',
    movementPattern: 'horizontal_push',
    primaryMuscles: ['chest', 'front_delts'],
    secondaryMuscles: ['triceps'],
    equipment: ['barbell', 'incline_bench', 'squat_rack'],
    difficulty: 'intermediate',
    jointStress: { shoulder: 'moderate', elbow: 'low' },
    defaultRestSeconds: 180,
    repRangeMin: 5,
    repRangeMax: 12,
    canBeSuperset: false,
    isUnilateral: false,
    youtubeVideoId: 'SrqOu55lrYU',
    videoStartTime: 0,
    videoEndTime: 35,
    similarExercises: ['incline-dumbbell-press', 'low-incline-bench-press'],
    requiresSpotter: true,
    highFatigueImpact: true,
  },
  {
    id: 'dumbbell-bench-press',
    name: 'Dumbbell Bench Press',
    category: 'compound',
    movementPattern: 'horizontal_push',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['front_delts', 'triceps'],
    equipment: ['dumbbell', 'bench'],
    difficulty: 'beginner',
    jointStress: { shoulder: 'low', elbow: 'low' },
    defaultRestSeconds: 120,
    repRangeMin: 6,
    repRangeMax: 15,
    canBeSuperset: false,
    isUnilateral: false,
    youtubeVideoId: 'VmB1G1K7v94',
    videoStartTime: 0,
    videoEndTime: 35,
    similarExercises: ['bench-press', 'machine-chest-press'],
    easierVariation: 'push-up',
  },
  {
    id: 'push-up',
    name: 'Push-Up',
    category: 'compound',
    movementPattern: 'horizontal_push',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['front_delts', 'triceps', 'abs'],
    equipment: ['bodyweight'],
    difficulty: 'beginner',
    jointStress: { shoulder: 'low', elbow: 'low', wrist: 'low' },
    defaultRestSeconds: 60,
    repRangeMin: 5,
    repRangeMax: 30,
    canBeSuperset: true,
    isUnilateral: false,
    youtubeVideoId: 'IODxDxX7oi4',
    videoStartTime: 0,
    videoEndTime: 35,
    similarExercises: ['dumbbell-bench-press', 'bench-press', 'machine-chest-press'],
    easierVariation: 'incline-push-up',
    harderVariation: 'decline-push-up',
  },
  {
    id: 'chest-fly',
    name: 'Chest Fly',
    category: 'isolation',
    movementPattern: 'horizontal_push',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['front_delts'],
    equipment: ['dumbbell', 'bench'],
    difficulty: 'beginner',
    jointStress: { shoulder: 'moderate' },
    defaultRestSeconds: 90,
    repRangeMin: 10,
    repRangeMax: 15,
    canBeSuperset: true,
    isUnilateral: false,
    youtubeVideoId: 'eozdVDA78K0',
    videoStartTime: 0,
    videoEndTime: 35,
    similarExercises: ['cable-fly', 'pec-deck'],
    goodForDropSets: true,
  },
  {
    id: 'incline-dumbbell-press',
    name: 'Incline Dumbbell Press',
    category: 'compound',
    movementPattern: 'horizontal_push',
    primaryMuscles: ['chest', 'front_delts'],
    secondaryMuscles: ['triceps'],
    equipment: ['dumbbell', 'incline_bench'],
    difficulty: 'beginner',
    jointStress: { shoulder: 'low', elbow: 'low' },
    defaultRestSeconds: 120,
    repRangeMin: 6,
    repRangeMax: 15,
    canBeSuperset: false,
    isUnilateral: false,
    similarExercises: ['incline-bench-press', 'incline-machine-press'],
  },
  {
    id: 'decline-bench-press',
    name: 'Decline Bench Press',
    category: 'compound',
    movementPattern: 'horizontal_push',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'front_delts'],
    equipment: ['barbell', 'decline_bench'],
    difficulty: 'intermediate',
    jointStress: { shoulder: 'low', elbow: 'low' },
    defaultRestSeconds: 150,
    repRangeMin: 6,
    repRangeMax: 12,
    canBeSuperset: false,
    isUnilateral: false,
    requiresSpotter: true,
    similarExercises: ['decline-dumbbell-press', 'dip'],
  },
  {
    id: 'cable-fly',
    name: 'Cable Fly',
    category: 'isolation',
    movementPattern: 'horizontal_push',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['front_delts'],
    equipment: ['cable'],
    difficulty: 'beginner',
    jointStress: { shoulder: 'low' },
    defaultRestSeconds: 60,
    repRangeMin: 10,
    repRangeMax: 20,
    canBeSuperset: true,
    isUnilateral: false,
    similarExercises: ['chest-fly', 'pec-deck'],
    goodForDropSets: true,
  },
  {
    id: 'machine-chest-press',
    name: 'Machine Chest Press',
    category: 'compound',
    movementPattern: 'horizontal_push',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'front_delts'],
    equipment: ['machine'],
    difficulty: 'beginner',
    jointStress: { shoulder: 'low', elbow: 'low' },
    defaultRestSeconds: 90,
    repRangeMin: 8,
    repRangeMax: 15,
    canBeSuperset: false,
    isUnilateral: false,
    similarExercises: ['bench-press', 'dumbbell-bench-press'],
    goodForDropSets: true,
  },
  {
    id: 'pec-deck',
    name: 'Pec Deck',
    category: 'isolation',
    movementPattern: 'horizontal_push',
    primaryMuscles: ['chest'],
    secondaryMuscles: [],
    equipment: ['machine'],
    difficulty: 'beginner',
    jointStress: { shoulder: 'low' },
    defaultRestSeconds: 60,
    repRangeMin: 10,
    repRangeMax: 20,
    canBeSuperset: true,
    isUnilateral: false,
    similarExercises: ['cable-fly', 'chest-fly'],
    goodForDropSets: true,
  },
  {
    id: 'incline-machine-press',
    name: 'Incline Machine Press',
    category: 'compound',
    movementPattern: 'horizontal_push',
    primaryMuscles: ['chest', 'front_delts'],
    secondaryMuscles: ['triceps'],
    equipment: ['machine'],
    difficulty: 'beginner',
    jointStress: { shoulder: 'low', elbow: 'low' },
    defaultRestSeconds: 90,
    repRangeMin: 8,
    repRangeMax: 15,
    canBeSuperset: false,
    isUnilateral: false,
    similarExercises: ['incline-dumbbell-press', 'incline-bench-press', 'machine-chest-press'],
    goodForDropSets: true,
  },
  {
    id: 'decline-dumbbell-press',
    name: 'Decline Dumbbell Press',
    category: 'compound',
    movementPattern: 'horizontal_push',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'front_delts'],
    equipment: ['dumbbell', 'decline_bench'],
    difficulty: 'intermediate',
    jointStress: { shoulder: 'low', elbow: 'low' },
    defaultRestSeconds: 120,
    repRangeMin: 8,
    repRangeMax: 12,
    canBeSuperset: false,
    isUnilateral: false,
    similarExercises: ['decline-bench-press', 'dumbbell-bench-press', 'dip'],
  },
  {
    id: 'close-grip-bench-press',
    name: 'Close Grip Bench Press',
    category: 'compound',
    movementPattern: 'horizontal_push',
    primaryMuscles: ['triceps', 'chest'],
    secondaryMuscles: ['front_delts'],
    equipment: ['barbell', 'bench', 'squat_rack'],
    difficulty: 'intermediate',
    jointStress: { shoulder: 'low', elbow: 'moderate' },
    defaultRestSeconds: 150,
    repRangeMin: 6,
    repRangeMax: 12,
    canBeSuperset: false,
    isUnilateral: false,
    requiresSpotter: true,
    similarExercises: ['bench-press', 'tricep-dip'],
  },
  {
    id: 'dip',
    name: 'Dip',
    category: 'compound',
    movementPattern: 'horizontal_push',
    primaryMuscles: ['chest', 'triceps'],
    secondaryMuscles: ['front_delts'],
    equipment: ['dip_station'],
    difficulty: 'intermediate',
    jointStress: { shoulder: 'moderate', elbow: 'low' },
    defaultRestSeconds: 120,
    repRangeMin: 5,
    repRangeMax: 15,
    canBeSuperset: false,
    isUnilateral: false,
    similarExercises: ['tricep-dip', 'decline-bench-press'],
    easierVariation: 'machine-dip',
    harderVariation: 'weighted-dip',
  },
  {
    id: 'bench-dip',
    name: 'Bench Dip',
    category: 'compound',
    movementPattern: 'horizontal_push',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['chest', 'front_delts'],
    equipment: ['bench'],
    difficulty: 'beginner',
    jointStress: { shoulder: 'moderate', elbow: 'low' },
    defaultRestSeconds: 60,
    repRangeMin: 8,
    repRangeMax: 20,
    canBeSuperset: true,
    isUnilateral: false,
    similarExercises: ['dip', 'tricep-dip', 'tricep-dip-machine'],
    harderVariation: 'dip',
  },
  {
    id: 'weighted-dip',
    name: 'Weighted Dip',
    category: 'compound',
    movementPattern: 'horizontal_push',
    primaryMuscles: ['chest', 'triceps'],
    secondaryMuscles: ['front_delts'],
    equipment: ['dip_station', 'dumbbell'],
    difficulty: 'advanced',
    jointStress: { shoulder: 'high', elbow: 'moderate' },
    defaultRestSeconds: 180,
    repRangeMin: 3,
    repRangeMax: 10,
    canBeSuperset: false,
    isUnilateral: false,
    similarExercises: ['dip', 'close-grip-bench-press', 'decline-bench-press'],
    easierVariation: 'dip',
    highFatigueImpact: true,
  },
  {
    id: 'svend-press',
    name: 'Svend Press',
    category: 'isolation',
    movementPattern: 'horizontal_push',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['front_delts'],
    equipment: ['barbell'], // plates
    difficulty: 'beginner',
    jointStress: { shoulder: 'low' },
    defaultRestSeconds: 60,
    repRangeMin: 12,
    repRangeMax: 20,
    canBeSuperset: true,
    isUnilateral: false,
    similarExercises: ['cable-fly', 'pec-deck', 'chest-fly'],
  },
];

// =============================================================================
// VERTICAL PUSH - Overhead press variations
// =============================================================================

const verticalPush: Exercise[] = [
  {
    id: 'overhead-press',
    name: 'Overhead Press',
    category: 'compound',
    movementPattern: 'vertical_push',
    primaryMuscles: ['front_delts', 'side_delts'],
    secondaryMuscles: ['triceps', 'upper_back'],
    equipment: ['barbell', 'squat_rack'],
    difficulty: 'intermediate',
    jointStress: { shoulder: 'high', lower_back: 'moderate' },
    defaultRestSeconds: 180,
    repRangeMin: 4,
    repRangeMax: 10,
    canBeSuperset: false,
    isUnilateral: false,
    youtubeVideoId: '2yjwXTZQDDI',
    videoStartTime: 0,
    videoEndTime: 35,
    similarExercises: ['dumbbell-shoulder-press', 'seated-overhead-press', 'push-press', 'z-press'],
    highFatigueImpact: true,
  },
  {
    id: 'dumbbell-shoulder-press',
    name: 'Dumbbell Shoulder Press',
    category: 'compound',
    movementPattern: 'vertical_push',
    primaryMuscles: ['front_delts', 'side_delts'],
    secondaryMuscles: ['triceps'],
    equipment: ['dumbbell', 'bench'],
    difficulty: 'beginner',
    jointStress: { shoulder: 'moderate' },
    defaultRestSeconds: 120,
    repRangeMin: 6,
    repRangeMax: 12,
    canBeSuperset: false,
    isUnilateral: false,
    youtubeVideoId: 'qEwKCR5JCog',
    videoStartTime: 0,
    videoEndTime: 35,
    similarExercises: ['overhead-press', 'arnold-press'],
  },
  {
    id: 'arnold-press',
    name: 'Arnold Press',
    category: 'compound',
    movementPattern: 'vertical_push',
    primaryMuscles: ['front_delts', 'side_delts'],
    secondaryMuscles: ['triceps'],
    equipment: ['dumbbell', 'bench'],
    difficulty: 'intermediate',
    jointStress: { shoulder: 'moderate' },
    defaultRestSeconds: 120,
    repRangeMin: 8,
    repRangeMax: 12,
    canBeSuperset: false,
    isUnilateral: false,
    similarExercises: ['dumbbell-shoulder-press', 'overhead-press', 'machine-shoulder-press'],
  },
  {
    id: 'seated-overhead-press',
    name: 'Seated Overhead Press',
    category: 'compound',
    movementPattern: 'vertical_push',
    primaryMuscles: ['front_delts', 'side_delts'],
    secondaryMuscles: ['triceps'],
    equipment: ['barbell', 'bench', 'squat_rack'],
    difficulty: 'intermediate',
    jointStress: { shoulder: 'high' },
    defaultRestSeconds: 150,
    repRangeMin: 5,
    repRangeMax: 10,
    canBeSuperset: false,
    isUnilateral: false,
    similarExercises: ['overhead-press', 'dumbbell-shoulder-press', 'z-press'],
    requiresSpotter: true,
  },
  {
    id: 'machine-shoulder-press',
    name: 'Machine Shoulder Press',
    category: 'compound',
    movementPattern: 'vertical_push',
    primaryMuscles: ['front_delts', 'side_delts'],
    secondaryMuscles: ['triceps'],
    equipment: ['machine'],
    difficulty: 'beginner',
    jointStress: { shoulder: 'low' },
    defaultRestSeconds: 90,
    repRangeMin: 8,
    repRangeMax: 15,
    canBeSuperset: false,
    isUnilateral: false,
    similarExercises: ['dumbbell-shoulder-press', 'overhead-press', 'arnold-press', 'landmine-press'],
    goodForDropSets: true,
  },
  {
    id: 'push-press',
    name: 'Push Press',
    category: 'compound',
    movementPattern: 'vertical_push',
    primaryMuscles: ['front_delts', 'side_delts'],
    secondaryMuscles: ['triceps', 'quads', 'glutes'],
    equipment: ['barbell', 'squat_rack'],
    difficulty: 'advanced',
    jointStress: { shoulder: 'high', lower_back: 'moderate', knee: 'low' },
    defaultRestSeconds: 180,
    repRangeMin: 3,
    repRangeMax: 8,
    canBeSuperset: false,
    isUnilateral: false,
    similarExercises: ['overhead-press', 'clean-and-press', 'z-press'],
    harderVariation: 'jerk',
    highFatigueImpact: true,
  },
  {
    id: 'landmine-press',
    name: 'Landmine Press',
    category: 'compound',
    movementPattern: 'vertical_push',
    primaryMuscles: ['front_delts', 'chest'],
    secondaryMuscles: ['triceps', 'abs'],
    equipment: ['barbell'],
    difficulty: 'intermediate',
    jointStress: { shoulder: 'low' },
    defaultRestSeconds: 90,
    repRangeMin: 8,
    repRangeMax: 12,
    canBeSuperset: true,
    isUnilateral: true,
    similarExercises: ['dumbbell-shoulder-press', 'arnold-press', 'machine-shoulder-press'],
  },
  {
    id: 'pike-push-up',
    name: 'Pike Push-Up',
    category: 'compound',
    movementPattern: 'vertical_push',
    primaryMuscles: ['front_delts'],
    secondaryMuscles: ['triceps', 'chest'],
    equipment: ['bodyweight'],
    difficulty: 'intermediate',
    jointStress: { shoulder: 'moderate', wrist: 'moderate' },
    defaultRestSeconds: 90,
    repRangeMin: 5,
    repRangeMax: 15,
    canBeSuperset: true,
    isUnilateral: false,
    similarExercises: ['handstand-push-up', 'dumbbell-shoulder-press'],
    easierVariation: 'push-up',
    harderVariation: 'handstand-push-up',
  },
  {
    id: 'z-press',
    name: 'Z-Press',
    category: 'compound',
    movementPattern: 'vertical_push',
    primaryMuscles: ['front_delts', 'side_delts'],
    secondaryMuscles: ['triceps', 'abs'],
    equipment: ['barbell'],
    optionalEquipment: ['dumbbell'],
    difficulty: 'advanced',
    jointStress: { shoulder: 'moderate', lower_back: 'low' },
    defaultRestSeconds: 150,
    repRangeMin: 5,
    repRangeMax: 10,
    canBeSuperset: false,
    isUnilateral: false,
    similarExercises: ['overhead-press', 'seated-overhead-press', 'dumbbell-shoulder-press'],
    highFatigueImpact: true,
  },
];

// =============================================================================
// HORIZONTAL PULL - Rows
// =============================================================================

const horizontalPull: Exercise[] = [
  {
    id: 'barbell-row',
    name: 'Barbell Row',
    category: 'compound',
    movementPattern: 'horizontal_pull',
    primaryMuscles: ['lats', 'upper_back'],
    secondaryMuscles: ['biceps', 'rear_delts', 'lower_back'],
    equipment: ['barbell'],
    difficulty: 'intermediate',
    jointStress: { lower_back: 'high' },
    defaultRestSeconds: 150,
    repRangeMin: 5,
    repRangeMax: 12,
    canBeSuperset: false,
    isUnilateral: false,
    youtubeVideoId: 'vT2GjY_Umpw',
    videoStartTime: 0,
    videoEndTime: 35,
    similarExercises: ['dumbbell-row', 'seated-row', 'pendlay-row', 't-bar-row'],
    highFatigueImpact: true,
  },
  {
    id: 'seated-row',
    name: 'Seated Row',
    category: 'compound',
    movementPattern: 'horizontal_pull',
    primaryMuscles: ['lats', 'upper_back'],
    secondaryMuscles: ['biceps', 'rear_delts'],
    equipment: ['cable'],
    difficulty: 'beginner',
    jointStress: { lower_back: 'low' },
    defaultRestSeconds: 90,
    repRangeMin: 8,
    repRangeMax: 15,
    canBeSuperset: false,
    isUnilateral: false,
    youtubeVideoId: 'GZbfZ033f74',
    videoStartTime: 0,
    videoEndTime: 35,
    similarExercises: ['barbell-row', 'dumbbell-row'],
    goodForDropSets: true,
  },
  {
    id: 'dumbbell-row',
    name: 'Dumbbell Row',
    category: 'compound',
    movementPattern: 'horizontal_pull',
    primaryMuscles: ['lats', 'upper_back'],
    secondaryMuscles: ['biceps', 'rear_delts'],
    equipment: ['dumbbell', 'bench'],
    difficulty: 'beginner',
    jointStress: { lower_back: 'low' },
    defaultRestSeconds: 90,
    repRangeMin: 8,
    repRangeMax: 15,
    canBeSuperset: true,
    isUnilateral: true,
    similarExercises: ['barbell-row', 'seated-row'],
  },
  {
    id: 'pendlay-row',
    name: 'Pendlay Row',
    category: 'compound',
    movementPattern: 'horizontal_pull',
    primaryMuscles: ['lats', 'upper_back'],
    secondaryMuscles: ['biceps', 'rear_delts', 'lower_back'],
    equipment: ['barbell'],
    difficulty: 'advanced',
    jointStress: { lower_back: 'high' },
    defaultRestSeconds: 180,
    repRangeMin: 3,
    repRangeMax: 8,
    canBeSuperset: false,
    isUnilateral: false,
    similarExercises: ['barbell-row', 'seal-row', 't-bar-row'],
    highFatigueImpact: true,
  },
  {
    id: 't-bar-row',
    name: 'T-Bar Row',
    category: 'compound',
    movementPattern: 'horizontal_pull',
    primaryMuscles: ['lats', 'upper_back'],
    secondaryMuscles: ['biceps', 'rear_delts'],
    equipment: ['barbell'],
    difficulty: 'intermediate',
    jointStress: { lower_back: 'moderate' },
    defaultRestSeconds: 120,
    repRangeMin: 6,
    repRangeMax: 12,
    canBeSuperset: false,
    isUnilateral: false,
    similarExercises: ['barbell-row', 'seated-row'],
  },
  {
    id: 'chest-supported-row',
    name: 'Chest Supported Row',
    category: 'compound',
    movementPattern: 'horizontal_pull',
    primaryMuscles: ['lats', 'upper_back'],
    secondaryMuscles: ['biceps', 'rear_delts'],
    equipment: ['dumbbell', 'incline_bench'],
    difficulty: 'beginner',
    jointStress: { lower_back: 'none' },
    defaultRestSeconds: 90,
    repRangeMin: 8,
    repRangeMax: 15,
    canBeSuperset: true,
    isUnilateral: false,
    similarExercises: ['dumbbell-row', 'machine-row'],
  },
  {
    id: 'machine-row',
    name: 'Machine Row',
    category: 'compound',
    movementPattern: 'horizontal_pull',
    primaryMuscles: ['lats', 'upper_back'],
    secondaryMuscles: ['biceps'],
    equipment: ['machine'],
    difficulty: 'beginner',
    jointStress: { lower_back: 'none' },
    defaultRestSeconds: 90,
    repRangeMin: 8,
    repRangeMax: 15,
    canBeSuperset: true,
    isUnilateral: false,
    similarExercises: ['seated-row', 'dumbbell-row', 'pendulum-row'],
    goodForDropSets: true,
  },
  {
    id: 'cable-row',
    name: 'Cable Row',
    category: 'compound',
    movementPattern: 'horizontal_pull',
    primaryMuscles: ['lats', 'upper_back'],
    secondaryMuscles: ['biceps', 'rear_delts'],
    equipment: ['cable'],
    difficulty: 'beginner',
    jointStress: { lower_back: 'low' },
    defaultRestSeconds: 90,
    repRangeMin: 8,
    repRangeMax: 15,
    canBeSuperset: true,
    isUnilateral: false,
    similarExercises: ['seated-row', 'dumbbell-row'],
    goodForDropSets: true,
  },
  {
    id: 'meadows-row',
    name: 'Meadows Row',
    category: 'compound',
    movementPattern: 'horizontal_pull',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['upper_back', 'biceps', 'rear_delts'],
    equipment: ['barbell'],
    difficulty: 'advanced',
    jointStress: { lower_back: 'moderate' },
    defaultRestSeconds: 90,
    repRangeMin: 8,
    repRangeMax: 12,
    canBeSuperset: true,
    isUnilateral: true,
    similarExercises: ['dumbbell-row', 't-bar-row'],
  },
  {
    id: 'inverted-row',
    name: 'Inverted Row',
    category: 'compound',
    movementPattern: 'horizontal_pull',
    primaryMuscles: ['lats', 'upper_back'],
    secondaryMuscles: ['biceps', 'rear_delts'],
    equipment: ['bodyweight', 'squat_rack'],
    difficulty: 'beginner',
    jointStress: {},
    defaultRestSeconds: 60,
    repRangeMin: 5,
    repRangeMax: 20,
    canBeSuperset: true,
    isUnilateral: false,
    similarExercises: ['dumbbell-row', 'machine-row'],
    easierVariation: 'incline-inverted-row',
    harderVariation: 'weighted-inverted-row',
  },
  {
    id: 'face-pull',
    name: 'Face Pull',
    category: 'isolation',
    movementPattern: 'horizontal_pull',
    primaryMuscles: ['rear_delts', 'upper_back'],
    secondaryMuscles: ['side_delts'],
    equipment: ['cable'],
    difficulty: 'beginner',
    jointStress: { shoulder: 'low' },
    defaultRestSeconds: 60,
    repRangeMin: 12,
    repRangeMax: 20,
    canBeSuperset: true,
    isUnilateral: false,
    similarExercises: ['rear-delt-fly', 'band-pull-apart'],
    goodForDropSets: true,
  },
  {
    id: 'seal-row',
    name: 'Seal Row',
    category: 'compound',
    movementPattern: 'horizontal_pull',
    primaryMuscles: ['lats', 'upper_back'],
    secondaryMuscles: ['biceps', 'rear_delts'],
    equipment: ['barbell', 'bench'],
    difficulty: 'intermediate',
    jointStress: { lower_back: 'none' },
    defaultRestSeconds: 120,
    repRangeMin: 6,
    repRangeMax: 12,
    canBeSuperset: false,
    isUnilateral: false,
    similarExercises: ['chest-supported-row', 'barbell-row'],
  },
  {
    id: 'pendulum-row',
    name: 'Pendulum Row',
    category: 'compound',
    movementPattern: 'horizontal_pull',
    primaryMuscles: ['lats', 'upper_back'],
    secondaryMuscles: ['biceps', 'rear_delts'],
    equipment: ['machine'],
    difficulty: 'beginner',
    jointStress: { lower_back: 'none' },
    defaultRestSeconds: 90,
    repRangeMin: 8,
    repRangeMax: 15,
    canBeSuperset: false,
    isUnilateral: false,
    similarExercises: ['machine-row', 'chest-supported-row', 'seated-row'],
    goodForDropSets: true,
  },
];

// =============================================================================
// VERTICAL PULL - Pull-ups, pulldowns
// =============================================================================

const verticalPull: Exercise[] = [
  {
    id: 'pull-up',
    name: 'Pull-Up',
    category: 'compound',
    movementPattern: 'vertical_pull',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['biceps', 'upper_back', 'rear_delts'],
    equipment: ['pull_up_bar'],
    difficulty: 'intermediate',
    jointStress: { shoulder: 'moderate', elbow: 'low' },
    defaultRestSeconds: 120,
    repRangeMin: 3,
    repRangeMax: 15,
    canBeSuperset: false,
    isUnilateral: false,
    youtubeVideoId: 'eGo4IYlbE5g',
    videoStartTime: 0,
    videoEndTime: 35,
    similarExercises: ['lat-pulldown', 'chin-up'],
    easierVariation: 'assisted-pull-up',
    harderVariation: 'weighted-pull-up',
  },
  {
    id: 'lat-pulldown',
    name: 'Lat Pulldown',
    category: 'compound',
    movementPattern: 'vertical_pull',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['biceps', 'upper_back'],
    equipment: ['lat_pulldown'],
    difficulty: 'beginner',
    jointStress: { shoulder: 'low' },
    defaultRestSeconds: 90,
    repRangeMin: 8,
    repRangeMax: 15,
    canBeSuperset: false,
    isUnilateral: false,
    youtubeVideoId: 'CAwf7n6Luuc',
    videoStartTime: 0,
    videoEndTime: 35,
    similarExercises: ['pull-up', 'close-grip-pulldown', 'neutral-grip-pulldown', 'single-arm-lat-pulldown'],
    goodForDropSets: true,
  },
  {
    id: 'chin-up',
    name: 'Chin-Up',
    category: 'compound',
    movementPattern: 'vertical_pull',
    primaryMuscles: ['lats', 'biceps'],
    secondaryMuscles: ['upper_back'],
    equipment: ['pull_up_bar'],
    difficulty: 'intermediate',
    jointStress: { shoulder: 'low', elbow: 'moderate' },
    defaultRestSeconds: 120,
    repRangeMin: 3,
    repRangeMax: 15,
    canBeSuperset: false,
    isUnilateral: false,
    similarExercises: ['pull-up', 'lat-pulldown'],
    easierVariation: 'assisted-chin-up',
    harderVariation: 'weighted-chin-up',
  },
  {
    id: 'close-grip-pulldown',
    name: 'Close Grip Pulldown',
    category: 'compound',
    movementPattern: 'vertical_pull',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['biceps', 'upper_back'],
    equipment: ['lat_pulldown'],
    difficulty: 'beginner',
    jointStress: { shoulder: 'low' },
    defaultRestSeconds: 90,
    repRangeMin: 8,
    repRangeMax: 15,
    canBeSuperset: false,
    isUnilateral: false,
    similarExercises: ['lat-pulldown', 'chin-up'],
    goodForDropSets: true,
  },
  {
    id: 'wide-grip-pulldown',
    name: 'Wide Grip Pulldown',
    category: 'compound',
    movementPattern: 'vertical_pull',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['biceps', 'upper_back', 'rear_delts'],
    equipment: ['lat_pulldown'],
    difficulty: 'beginner',
    jointStress: { shoulder: 'moderate' },
    defaultRestSeconds: 90,
    repRangeMin: 8,
    repRangeMax: 15,
    canBeSuperset: false,
    isUnilateral: false,
    similarExercises: ['lat-pulldown', 'pull-up'],
    goodForDropSets: true,
  },
  {
    id: 'straight-arm-pulldown',
    name: 'Straight Arm Pulldown',
    category: 'isolation',
    movementPattern: 'vertical_pull',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['abs'],
    equipment: ['cable'],
    difficulty: 'beginner',
    jointStress: { shoulder: 'low' },
    defaultRestSeconds: 60,
    repRangeMin: 12,
    repRangeMax: 20,
    canBeSuperset: true,
    isUnilateral: false,
    similarExercises: ['lat-pulldown', 'dumbbell-pullover'],
    goodForDropSets: true,
  },
  {
    id: 'assisted-pull-up',
    name: 'Assisted Pull-Up',
    category: 'compound',
    movementPattern: 'vertical_pull',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['biceps', 'upper_back'],
    equipment: ['machine', 'pull_up_bar'],
    difficulty: 'beginner',
    jointStress: { shoulder: 'low' },
    defaultRestSeconds: 90,
    repRangeMin: 6,
    repRangeMax: 15,
    canBeSuperset: false,
    isUnilateral: false,
    similarExercises: ['lat-pulldown', 'pull-up'],
    harderVariation: 'pull-up',
  },
  {
    id: 'dumbbell-pullover',
    name: 'Dumbbell Pullover',
    category: 'isolation',
    movementPattern: 'vertical_pull',
    primaryMuscles: ['lats', 'chest'],
    secondaryMuscles: ['triceps'],
    equipment: ['dumbbell', 'bench'],
    difficulty: 'intermediate',
    jointStress: { shoulder: 'moderate' },
    defaultRestSeconds: 90,
    repRangeMin: 10,
    repRangeMax: 15,
    canBeSuperset: true,
    isUnilateral: false,
    similarExercises: ['straight-arm-pulldown'],
  },
  {
    id: 'single-arm-lat-pulldown',
    name: 'Single Arm Lat Pulldown',
    category: 'compound',
    movementPattern: 'vertical_pull',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['biceps', 'upper_back'],
    equipment: ['cable'],
    difficulty: 'beginner',
    jointStress: { shoulder: 'low' },
    defaultRestSeconds: 60,
    repRangeMin: 10,
    repRangeMax: 15,
    canBeSuperset: true,
    isUnilateral: true,
    similarExercises: ['lat-pulldown', 'close-grip-pulldown', 'straight-arm-pulldown'],
    goodForDropSets: true,
  },
  {
    id: 'neutral-grip-pulldown',
    name: 'Neutral Grip Pulldown',
    category: 'compound',
    movementPattern: 'vertical_pull',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['biceps', 'upper_back'],
    equipment: ['lat_pulldown'],
    difficulty: 'beginner',
    jointStress: { shoulder: 'low', elbow: 'low' },
    defaultRestSeconds: 90,
    repRangeMin: 8,
    repRangeMax: 15,
    canBeSuperset: false,
    isUnilateral: false,
    similarExercises: ['close-grip-pulldown', 'lat-pulldown', 'chin-up'],
    goodForDropSets: true,
  },
];

// =============================================================================
// SQUAT PATTERNS
// =============================================================================

const squatPatterns: Exercise[] = [
  {
    id: 'squat',
    name: 'Squat',
    category: 'compound',
    movementPattern: 'squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'lower_back', 'abs'],
    equipment: ['barbell', 'squat_rack'],
    difficulty: 'intermediate',
    jointStress: { knee: 'moderate', hip: 'moderate', lower_back: 'moderate' },
    defaultRestSeconds: 180,
    repRangeMin: 3,
    repRangeMax: 12,
    canBeSuperset: false,
    isUnilateral: false,
    youtubeVideoId: 'aclHkVaku9U',
    videoStartTime: 0,
    videoEndTime: 35,
    similarExercises: ['front-squat', 'leg-press', 'safety-bar-squat', 'smith-machine-squat'],
    easierVariation: 'goblet-squat',
    highFatigueImpact: true,
    requiresSpotter: true,
  },
  {
    id: 'front-squat',
    name: 'Front Squat',
    category: 'compound',
    movementPattern: 'squat',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes', 'abs', 'upper_back'],
    equipment: ['barbell', 'squat_rack'],
    difficulty: 'advanced',
    jointStress: { knee: 'moderate', hip: 'low', wrist: 'moderate' },
    defaultRestSeconds: 180,
    repRangeMin: 3,
    repRangeMax: 10,
    canBeSuperset: false,
    isUnilateral: false,
    youtubeVideoId: 'v-mQm_droHg',
    videoStartTime: 0,
    videoEndTime: 35,
    similarExercises: ['squat', 'goblet-squat'],
    highFatigueImpact: true,
  },
  {
    id: 'leg-press',
    name: 'Leg Press',
    category: 'compound',
    movementPattern: 'squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: ['leg_press'],
    difficulty: 'beginner',
    jointStress: { knee: 'moderate', lower_back: 'low' },
    defaultRestSeconds: 120,
    repRangeMin: 8,
    repRangeMax: 20,
    canBeSuperset: false,
    isUnilateral: false,
    youtubeVideoId: 'IZxyjW7MPJQ',
    videoStartTime: 0,
    videoEndTime: 35,
    similarExercises: ['squat', 'hack-squat', 'belt-squat', 'smith-machine-squat'],
    goodForDropSets: true,
  },
  {
    id: 'goblet-squat',
    name: 'Goblet Squat',
    category: 'compound',
    movementPattern: 'squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['abs'],
    equipment: ['dumbbell'],
    optionalEquipment: ['kettlebell'],
    difficulty: 'beginner',
    jointStress: { knee: 'low', hip: 'low' },
    defaultRestSeconds: 90,
    repRangeMin: 8,
    repRangeMax: 15,
    canBeSuperset: false,
    isUnilateral: false,
    similarExercises: ['squat', 'front-squat'],
    harderVariation: 'front-squat',
  },
  {
    id: 'hack-squat',
    name: 'Hack Squat',
    category: 'compound',
    movementPattern: 'squat',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes'],
    equipment: ['machine'],
    difficulty: 'beginner',
    jointStress: { knee: 'moderate', lower_back: 'none' },
    defaultRestSeconds: 120,
    repRangeMin: 8,
    repRangeMax: 15,
    canBeSuperset: false,
    isUnilateral: false,
    similarExercises: ['leg-press', 'squat', 'belt-squat', 'smith-machine-squat'],
    goodForDropSets: true,
  },
  {
    id: 'smith-machine-squat',
    name: 'Smith Machine Squat',
    category: 'compound',
    movementPattern: 'squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: ['smith_machine'],
    difficulty: 'beginner',
    jointStress: { knee: 'moderate', lower_back: 'low' },
    defaultRestSeconds: 120,
    repRangeMin: 8,
    repRangeMax: 15,
    canBeSuperset: false,
    isUnilateral: false,
    similarExercises: ['squat', 'leg-press', 'hack-squat'],
  },
  {
    id: 'sissy-squat',
    name: 'Sissy Squat',
    category: 'isolation',
    movementPattern: 'squat',
    primaryMuscles: ['quads'],
    secondaryMuscles: [],
    equipment: ['bodyweight'],
    difficulty: 'advanced',
    jointStress: { knee: 'high' },
    defaultRestSeconds: 90,
    repRangeMin: 8,
    repRangeMax: 15,
    canBeSuperset: true,
    isUnilateral: false,
    similarExercises: ['leg-extension'],
  },
  {
    id: 'box-squat',
    name: 'Box Squat',
    category: 'compound',
    movementPattern: 'squat',
    primaryMuscles: ['quads', 'glutes', 'hamstrings'],
    secondaryMuscles: ['lower_back'],
    equipment: ['barbell', 'squat_rack', 'bench'],
    difficulty: 'intermediate',
    jointStress: { knee: 'low', hip: 'moderate', lower_back: 'moderate' },
    defaultRestSeconds: 180,
    repRangeMin: 3,
    repRangeMax: 8,
    canBeSuperset: false,
    isUnilateral: false,
    similarExercises: ['squat', 'safety-bar-squat', 'pause-squat'],
    goodForPauseReps: true,
  },
  {
    id: 'pause-squat',
    name: 'Pause Squat',
    category: 'compound',
    movementPattern: 'squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'lower_back', 'abs'],
    equipment: ['barbell', 'squat_rack'],
    difficulty: 'advanced',
    jointStress: { knee: 'moderate', hip: 'moderate', lower_back: 'moderate' },
    defaultRestSeconds: 180,
    repRangeMin: 2,
    repRangeMax: 6,
    canBeSuperset: false,
    isUnilateral: false,
    similarExercises: ['squat', 'front-squat', 'box-squat'],
    requiresSpotter: true,
    highFatigueImpact: true,
    goodForPauseReps: true,
  },
  {
    id: 'bodyweight-squat',
    name: 'Bodyweight Squat',
    category: 'compound',
    movementPattern: 'squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: ['bodyweight'],
    difficulty: 'beginner',
    jointStress: { knee: 'low', hip: 'low' },
    defaultRestSeconds: 60,
    repRangeMin: 10,
    repRangeMax: 30,
    canBeSuperset: true,
    isUnilateral: false,
    similarExercises: ['goblet-squat'],
    harderVariation: 'goblet-squat',
  },
  {
    id: 'belt-squat',
    name: 'Belt Squat',
    category: 'compound',
    movementPattern: 'squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: ['machine'],
    difficulty: 'intermediate',
    jointStress: { knee: 'moderate', lower_back: 'none' },
    defaultRestSeconds: 120,
    repRangeMin: 6,
    repRangeMax: 15,
    canBeSuperset: false,
    isUnilateral: false,
    similarExercises: ['squat', 'hack-squat', 'leg-press'],
    goodForDropSets: true,
  },
  {
    id: 'safety-bar-squat',
    name: 'Safety Bar Squat',
    category: 'compound',
    movementPattern: 'squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'lower_back', 'abs', 'upper_back'],
    equipment: ['barbell', 'squat_rack'],
    difficulty: 'intermediate',
    jointStress: { knee: 'moderate', hip: 'moderate', lower_back: 'moderate' },
    defaultRestSeconds: 180,
    repRangeMin: 3,
    repRangeMax: 10,
    canBeSuperset: false,
    isUnilateral: false,
    similarExercises: ['squat', 'front-squat', 'box-squat'],
    highFatigueImpact: true,
    requiresSpotter: true,
  },
];

// =============================================================================
// HINGE PATTERNS - Deadlifts, RDLs, hip thrusts
// =============================================================================

const hingePatterns: Exercise[] = [
  {
    id: 'deadlift',
    name: 'Deadlift',
    category: 'compound',
    movementPattern: 'hinge',
    primaryMuscles: ['hamstrings', 'glutes', 'lower_back'],
    secondaryMuscles: ['lats', 'upper_back', 'quads', 'forearms'],
    equipment: ['barbell'],
    difficulty: 'intermediate',
    jointStress: { lower_back: 'high', hip: 'moderate' },
    defaultRestSeconds: 180,
    repRangeMin: 1,
    repRangeMax: 8,
    canBeSuperset: false,
    isUnilateral: false,
    youtubeVideoId: 'ytGaGIn3SjE',
    videoStartTime: 0,
    videoEndTime: 35,
    similarExercises: ['romanian-deadlift', 'trap-bar-deadlift', 'sumo-deadlift'],
    highFatigueImpact: true,
  },
  {
    id: 'romanian-deadlift',
    name: 'Romanian Deadlift',
    category: 'compound',
    movementPattern: 'hinge',
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['lower_back'],
    equipment: ['barbell'],
    optionalEquipment: ['dumbbell'],
    difficulty: 'intermediate',
    jointStress: { lower_back: 'moderate', hip: 'low' },
    defaultRestSeconds: 120,
    repRangeMin: 6,
    repRangeMax: 12,
    canBeSuperset: false,
    isUnilateral: false,
    youtubeVideoId: '0zv6zO2pA9k',
    videoStartTime: 0,
    videoEndTime: 35,
    similarExercises: ['stiff-leg-deadlift', 'dumbbell-rdl'],
  },
  {
    id: 'hip-thrust',
    name: 'Hip Thrust',
    category: 'compound',
    movementPattern: 'hinge',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: ['barbell', 'bench'],
    difficulty: 'beginner',
    jointStress: { hip: 'low', lower_back: 'low' },
    defaultRestSeconds: 120,
    repRangeMin: 8,
    repRangeMax: 15,
    canBeSuperset: false,
    isUnilateral: false,
    similarExercises: ['glute-bridge', 'cable-pull-through', 'hip-thrust-machine'],
    goodForPauseReps: true,
  },
  {
    id: 'trap-bar-deadlift',
    name: 'Trap Bar Deadlift',
    category: 'compound',
    movementPattern: 'hinge',
    primaryMuscles: ['quads', 'glutes', 'hamstrings'],
    secondaryMuscles: ['lower_back', 'upper_back'],
    equipment: ['trap_bar'],
    difficulty: 'beginner',
    jointStress: { lower_back: 'moderate', hip: 'low' },
    defaultRestSeconds: 180,
    repRangeMin: 3,
    repRangeMax: 10,
    canBeSuperset: false,
    isUnilateral: false,
    similarExercises: ['deadlift', 'squat'],
    highFatigueImpact: true,
  },
  {
    id: 'stiff-leg-deadlift',
    name: 'Stiff Leg Deadlift',
    category: 'compound',
    movementPattern: 'hinge',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: ['glutes', 'lower_back'],
    equipment: ['barbell'],
    difficulty: 'intermediate',
    jointStress: { lower_back: 'high' },
    defaultRestSeconds: 120,
    repRangeMin: 6,
    repRangeMax: 12,
    canBeSuperset: false,
    isUnilateral: false,
    similarExercises: ['romanian-deadlift', 'dumbbell-rdl', 'deadlift'],
  },
  {
    id: 'dumbbell-rdl',
    name: 'Dumbbell RDL',
    category: 'compound',
    movementPattern: 'hinge',
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['lower_back'],
    equipment: ['dumbbell'],
    difficulty: 'beginner',
    jointStress: { lower_back: 'low', hip: 'low' },
    defaultRestSeconds: 90,
    repRangeMin: 8,
    repRangeMax: 15,
    canBeSuperset: false,
    isUnilateral: false,
    similarExercises: ['romanian-deadlift', 'single-leg-rdl'],
  },
  {
    id: 'single-leg-rdl',
    name: 'Single Leg RDL',
    category: 'compound',
    movementPattern: 'hinge',
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['lower_back'],
    equipment: ['dumbbell'],
    optionalEquipment: ['kettlebell'],
    difficulty: 'intermediate',
    jointStress: { lower_back: 'low', hip: 'low' },
    defaultRestSeconds: 90,
    repRangeMin: 8,
    repRangeMax: 12,
    canBeSuperset: true,
    isUnilateral: true,
    similarExercises: ['dumbbell-rdl', 'romanian-deadlift'],
  },
  {
    id: 'glute-bridge',
    name: 'Glute Bridge',
    category: 'compound',
    movementPattern: 'hinge',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: ['bodyweight'],
    optionalEquipment: ['barbell', 'dumbbell'],
    difficulty: 'beginner',
    jointStress: {},
    defaultRestSeconds: 60,
    repRangeMin: 12,
    repRangeMax: 20,
    canBeSuperset: true,
    isUnilateral: false,
    similarExercises: ['hip-thrust', 'hip-thrust-machine'],
    harderVariation: 'hip-thrust',
  },
  {
    id: 'cable-pull-through',
    name: 'Cable Pull Through',
    category: 'compound',
    movementPattern: 'hinge',
    primaryMuscles: ['glutes', 'hamstrings'],
    secondaryMuscles: [],
    equipment: ['cable'],
    difficulty: 'beginner',
    jointStress: { lower_back: 'low' },
    defaultRestSeconds: 60,
    repRangeMin: 12,
    repRangeMax: 20,
    canBeSuperset: true,
    isUnilateral: false,
    similarExercises: ['hip-thrust', 'romanian-deadlift'],
    goodForDropSets: true,
  },
  {
    id: 'good-morning',
    name: 'Good Morning',
    category: 'compound',
    movementPattern: 'hinge',
    primaryMuscles: ['hamstrings', 'lower_back'],
    secondaryMuscles: ['glutes'],
    equipment: ['barbell', 'squat_rack'],
    difficulty: 'advanced',
    jointStress: { lower_back: 'high' },
    defaultRestSeconds: 120,
    repRangeMin: 6,
    repRangeMax: 12,
    canBeSuperset: false,
    isUnilateral: false,
    similarExercises: ['romanian-deadlift', 'stiff-leg-deadlift'],
  },
  {
    id: 'hip-thrust-machine',
    name: 'Hip Thrust Machine',
    category: 'compound',
    movementPattern: 'hinge',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: ['machine'],
    difficulty: 'beginner',
    jointStress: { hip: 'low', lower_back: 'none' },
    defaultRestSeconds: 90,
    repRangeMin: 8,
    repRangeMax: 20,
    canBeSuperset: false,
    isUnilateral: false,
    similarExercises: ['hip-thrust', 'glute-bridge', 'cable-pull-through'],
    goodForDropSets: true,
    goodForPauseReps: true,
  },
  {
    id: 'sumo-deadlift',
    name: 'Sumo Deadlift',
    category: 'compound',
    movementPattern: 'hinge',
    primaryMuscles: ['glutes', 'quads', 'hamstrings'],
    secondaryMuscles: ['lower_back', 'adductors', 'upper_back'],
    equipment: ['barbell'],
    difficulty: 'intermediate',
    jointStress: { hip: 'moderate', lower_back: 'moderate', knee: 'low' },
    defaultRestSeconds: 180,
    repRangeMin: 1,
    repRangeMax: 8,
    canBeSuperset: false,
    isUnilateral: false,
    similarExercises: ['deadlift', 'trap-bar-deadlift', 'romanian-deadlift'],
    highFatigueImpact: true,
  },
];

// =============================================================================
// LUNGE PATTERNS - Unilateral leg work
// =============================================================================

const lungePatterns: Exercise[] = [
  {
    id: 'lunges',
    name: 'Lunges',
    category: 'compound',
    movementPattern: 'lunge',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: ['bodyweight'],
    optionalEquipment: ['dumbbell', 'barbell'],
    difficulty: 'beginner',
    jointStress: { knee: 'moderate', hip: 'low' },
    defaultRestSeconds: 90,
    repRangeMin: 8,
    repRangeMax: 15,
    canBeSuperset: true,
    isUnilateral: true,
    youtubeVideoId: 'wrwwXE_x-pQ',
    videoStartTime: 0,
    videoEndTime: 35,
    similarExercises: ['walking-lunges', 'reverse-lunges'],
  },
  {
    id: 'bulgarian-split-squat',
    name: 'Bulgarian Split Squat',
    category: 'compound',
    movementPattern: 'lunge',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: ['bodyweight', 'bench'],
    optionalEquipment: ['dumbbell', 'barbell'],
    difficulty: 'intermediate',
    jointStress: { knee: 'moderate', hip: 'moderate' },
    defaultRestSeconds: 90,
    repRangeMin: 6,
    repRangeMax: 12,
    canBeSuperset: false,
    isUnilateral: true,
    similarExercises: ['lunges', 'step-up'],
  },
  {
    id: 'walking-lunges',
    name: 'Walking Lunges',
    category: 'compound',
    movementPattern: 'lunge',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: ['bodyweight'],
    optionalEquipment: ['dumbbell'],
    difficulty: 'beginner',
    jointStress: { knee: 'moderate' },
    defaultRestSeconds: 90,
    repRangeMin: 8,
    repRangeMax: 15,
    canBeSuperset: true,
    isUnilateral: true,
    similarExercises: ['lunges', 'reverse-lunges'],
  },
  {
    id: 'reverse-lunges',
    name: 'Reverse Lunges',
    category: 'compound',
    movementPattern: 'lunge',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: ['bodyweight'],
    optionalEquipment: ['dumbbell', 'barbell'],
    difficulty: 'beginner',
    jointStress: { knee: 'low', hip: 'low' },
    defaultRestSeconds: 90,
    repRangeMin: 8,
    repRangeMax: 15,
    canBeSuperset: true,
    isUnilateral: true,
    similarExercises: ['lunges', 'walking-lunges'],
  },
  {
    id: 'step-up',
    name: 'Step-Up',
    category: 'compound',
    movementPattern: 'lunge',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: ['bodyweight', 'bench'],
    optionalEquipment: ['dumbbell'],
    difficulty: 'beginner',
    jointStress: { knee: 'low' },
    defaultRestSeconds: 90,
    repRangeMin: 8,
    repRangeMax: 15,
    canBeSuperset: true,
    isUnilateral: true,
    similarExercises: ['lunges', 'bulgarian-split-squat'],
  },
  {
    id: 'lateral-lunge',
    name: 'Lateral Lunge',
    category: 'compound',
    movementPattern: 'lunge',
    primaryMuscles: ['quads', 'glutes', 'adductors'],
    secondaryMuscles: ['hamstrings'],
    equipment: ['bodyweight'],
    optionalEquipment: ['dumbbell'],
    difficulty: 'intermediate',
    jointStress: { knee: 'moderate', hip: 'low' },
    defaultRestSeconds: 90,
    repRangeMin: 8,
    repRangeMax: 12,
    canBeSuperset: true,
    isUnilateral: true,
    similarExercises: ['lunges', 'cossack-squat'],
  },
  {
    id: 'cossack-squat',
    name: 'Cossack Squat',
    category: 'compound',
    movementPattern: 'lunge',
    primaryMuscles: ['quads', 'adductors', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: ['bodyweight'],
    optionalEquipment: ['dumbbell', 'kettlebell'],
    difficulty: 'advanced',
    jointStress: { knee: 'moderate', hip: 'moderate' },
    defaultRestSeconds: 90,
    repRangeMin: 6,
    repRangeMax: 12,
    canBeSuperset: true,
    isUnilateral: true,
    similarExercises: ['lateral-lunge'],
  },
  {
    id: 'deficit-reverse-lunge',
    name: 'Deficit Reverse Lunge',
    category: 'compound',
    movementPattern: 'lunge',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: ['bodyweight'],
    optionalEquipment: ['dumbbell'],
    difficulty: 'intermediate',
    jointStress: { knee: 'moderate', hip: 'moderate' },
    defaultRestSeconds: 90,
    repRangeMin: 6,
    repRangeMax: 12,
    canBeSuperset: true,
    isUnilateral: true,
    similarExercises: ['reverse-lunges', 'bulgarian-split-squat'],
  },
];

// =============================================================================
// ISOLATION ARMS - Biceps and triceps
// =============================================================================

const isolationArms: Exercise[] = [
  {
    id: 'bicep-curl',
    name: 'Bicep Curl',
    category: 'isolation',
    movementPattern: 'isolation_pull',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    equipment: ['dumbbell'],
    optionalEquipment: ['barbell', 'ez_bar'],
    difficulty: 'beginner',
    jointStress: { elbow: 'low' },
    defaultRestSeconds: 60,
    repRangeMin: 8,
    repRangeMax: 15,
    canBeSuperset: true,
    isUnilateral: false,
    youtubeVideoId: 'ykJmrZ5v0Oo',
    videoStartTime: 0,
    videoEndTime: 35,
    similarExercises: ['hammer-curl', 'barbell-curl'],
    goodForDropSets: true,
  },
  {
    id: 'hammer-curl',
    name: 'Hammer Curl',
    category: 'isolation',
    movementPattern: 'isolation_pull',
    primaryMuscles: ['biceps', 'forearms'],
    secondaryMuscles: [],
    equipment: ['dumbbell'],
    difficulty: 'beginner',
    jointStress: { elbow: 'low' },
    defaultRestSeconds: 60,
    repRangeMin: 8,
    repRangeMax: 15,
    canBeSuperset: true,
    isUnilateral: false,
    youtubeVideoId: 'zC3nLlEvin4',
    videoStartTime: 0,
    videoEndTime: 35,
    similarExercises: ['bicep-curl', 'cross-body-curl'],
    goodForDropSets: true,
  },
  {
    id: 'tricep-pushdown',
    name: 'Tricep Pushdown',
    category: 'isolation',
    movementPattern: 'isolation_push',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    equipment: ['cable'],
    difficulty: 'beginner',
    jointStress: { elbow: 'low' },
    defaultRestSeconds: 60,
    repRangeMin: 10,
    repRangeMax: 20,
    canBeSuperset: true,
    isUnilateral: false,
    youtubeVideoId: '2-LAMcpzODU',
    videoStartTime: 0,
    videoEndTime: 35,
    similarExercises: ['rope-pushdown', 'overhead-tricep-extension', 'overhead-cable-tricep-extension'],
    goodForDropSets: true,
  },
  {
    id: 'tricep-dip',
    name: 'Tricep Dip',
    category: 'compound',
    movementPattern: 'isolation_push',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['chest', 'front_delts'],
    equipment: ['dip_station'],
    optionalEquipment: ['bench'],
    difficulty: 'intermediate',
    jointStress: { shoulder: 'moderate', elbow: 'moderate' },
    defaultRestSeconds: 90,
    repRangeMin: 6,
    repRangeMax: 15,
    canBeSuperset: false,
    isUnilateral: false,
    youtubeVideoId: '6kALZikXxLc',
    videoStartTime: 0,
    videoEndTime: 35,
    similarExercises: ['close-grip-bench-press', 'dip', 'tricep-dip-machine'],
    easierVariation: 'bench-dip',
    harderVariation: 'weighted-dip',
  },
  {
    id: 'barbell-curl',
    name: 'Barbell Curl',
    category: 'isolation',
    movementPattern: 'isolation_pull',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    equipment: ['barbell'],
    optionalEquipment: ['ez_bar'],
    difficulty: 'beginner',
    jointStress: { elbow: 'low', wrist: 'low' },
    defaultRestSeconds: 90,
    repRangeMin: 6,
    repRangeMax: 12,
    canBeSuperset: true,
    isUnilateral: false,
    similarExercises: ['bicep-curl', 'ez-bar-curl'],
    goodForDropSets: true,
  },
  {
    id: 'ez-bar-curl',
    name: 'EZ Bar Curl',
    category: 'isolation',
    movementPattern: 'isolation_pull',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    equipment: ['ez_bar'],
    difficulty: 'beginner',
    jointStress: { elbow: 'low' },
    defaultRestSeconds: 90,
    repRangeMin: 8,
    repRangeMax: 12,
    canBeSuperset: true,
    isUnilateral: false,
    similarExercises: ['barbell-curl', 'bicep-curl'],
    goodForDropSets: true,
  },
  {
    id: 'preacher-curl',
    name: 'Preacher Curl',
    category: 'isolation',
    movementPattern: 'isolation_pull',
    primaryMuscles: ['biceps'],
    secondaryMuscles: [],
    equipment: ['ez_bar', 'bench'],
    optionalEquipment: ['dumbbell'],
    difficulty: 'beginner',
    jointStress: { elbow: 'low' },
    defaultRestSeconds: 60,
    repRangeMin: 8,
    repRangeMax: 15,
    canBeSuperset: true,
    isUnilateral: false,
    similarExercises: ['bicep-curl', 'concentration-curl'],
    goodForDropSets: true,
  },
  {
    id: 'concentration-curl',
    name: 'Concentration Curl',
    category: 'isolation',
    movementPattern: 'isolation_pull',
    primaryMuscles: ['biceps'],
    secondaryMuscles: [],
    equipment: ['dumbbell'],
    difficulty: 'beginner',
    jointStress: { elbow: 'low' },
    defaultRestSeconds: 60,
    repRangeMin: 10,
    repRangeMax: 15,
    canBeSuperset: true,
    isUnilateral: true,
    similarExercises: ['bicep-curl', 'preacher-curl'],
    goodForDropSets: true,
  },
  {
    id: 'incline-dumbbell-curl',
    name: 'Incline Dumbbell Curl',
    category: 'isolation',
    movementPattern: 'isolation_pull',
    primaryMuscles: ['biceps'],
    secondaryMuscles: [],
    equipment: ['dumbbell', 'incline_bench'],
    difficulty: 'intermediate',
    jointStress: { elbow: 'low' },
    defaultRestSeconds: 60,
    repRangeMin: 8,
    repRangeMax: 15,
    canBeSuperset: true,
    isUnilateral: false,
    similarExercises: ['bicep-curl', 'spider-curl', 'preacher-curl'],
    goodForDropSets: true,
  },
  {
    id: 'cable-curl',
    name: 'Cable Curl',
    category: 'isolation',
    movementPattern: 'isolation_pull',
    primaryMuscles: ['biceps'],
    secondaryMuscles: [],
    equipment: ['cable'],
    difficulty: 'beginner',
    jointStress: { elbow: 'low' },
    defaultRestSeconds: 60,
    repRangeMin: 10,
    repRangeMax: 20,
    canBeSuperset: true,
    isUnilateral: false,
    similarExercises: ['bicep-curl', 'barbell-curl', 'preacher-curl-machine'],
    goodForDropSets: true,
  },
  {
    id: 'rope-pushdown',
    name: 'Rope Pushdown',
    category: 'isolation',
    movementPattern: 'isolation_push',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    equipment: ['cable'],
    difficulty: 'beginner',
    jointStress: { elbow: 'low' },
    defaultRestSeconds: 60,
    repRangeMin: 10,
    repRangeMax: 20,
    canBeSuperset: true,
    isUnilateral: false,
    similarExercises: ['tricep-pushdown', 'overhead-tricep-extension'],
    goodForDropSets: true,
  },
  {
    id: 'overhead-tricep-extension',
    name: 'Overhead Tricep Extension',
    category: 'isolation',
    movementPattern: 'isolation_push',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    equipment: ['dumbbell'],
    optionalEquipment: ['cable', 'ez_bar'],
    difficulty: 'beginner',
    jointStress: { elbow: 'low', shoulder: 'low' },
    defaultRestSeconds: 60,
    repRangeMin: 10,
    repRangeMax: 15,
    canBeSuperset: true,
    isUnilateral: false,
    similarExercises: ['tricep-pushdown', 'skull-crusher'],
    goodForDropSets: true,
  },
  {
    id: 'skull-crusher',
    name: 'Skull Crusher',
    category: 'isolation',
    movementPattern: 'isolation_push',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    equipment: ['ez_bar', 'bench'],
    optionalEquipment: ['barbell', 'dumbbell'],
    difficulty: 'intermediate',
    jointStress: { elbow: 'moderate' },
    defaultRestSeconds: 90,
    repRangeMin: 8,
    repRangeMax: 12,
    canBeSuperset: true,
    isUnilateral: false,
    similarExercises: ['overhead-tricep-extension', 'close-grip-bench-press'],
  },
  {
    id: 'kickback',
    name: 'Kickback',
    category: 'isolation',
    movementPattern: 'isolation_push',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    equipment: ['dumbbell'],
    optionalEquipment: ['cable'],
    difficulty: 'beginner',
    jointStress: { elbow: 'low' },
    defaultRestSeconds: 60,
    repRangeMin: 10,
    repRangeMax: 15,
    canBeSuperset: true,
    isUnilateral: true,
    similarExercises: ['tricep-pushdown', 'overhead-tricep-extension'],
    goodForDropSets: true,
  },
  {
    id: 'wrist-curl',
    name: 'Wrist Curl',
    category: 'isolation',
    movementPattern: 'isolation_pull',
    primaryMuscles: ['forearms'],
    secondaryMuscles: [],
    equipment: ['dumbbell'],
    optionalEquipment: ['barbell'],
    difficulty: 'beginner',
    jointStress: { wrist: 'low' },
    defaultRestSeconds: 45,
    repRangeMin: 15,
    repRangeMax: 25,
    canBeSuperset: true,
    isUnilateral: false,
    similarExercises: ['reverse-wrist-curl', 'reverse-barbell-curl'],
    goodForDropSets: true,
  },
  {
    id: 'reverse-wrist-curl',
    name: 'Reverse Wrist Curl',
    category: 'isolation',
    movementPattern: 'isolation_pull',
    primaryMuscles: ['forearms'],
    secondaryMuscles: [],
    equipment: ['dumbbell'],
    optionalEquipment: ['barbell'],
    difficulty: 'beginner',
    jointStress: { wrist: 'low' },
    defaultRestSeconds: 45,
    repRangeMin: 15,
    repRangeMax: 25,
    canBeSuperset: true,
    isUnilateral: false,
    similarExercises: ['wrist-curl', 'reverse-barbell-curl'],
    goodForDropSets: true,
  },
  {
    id: 'reverse-barbell-curl',
    name: 'Reverse Barbell Curl',
    category: 'isolation',
    movementPattern: 'isolation_pull',
    primaryMuscles: ['forearms'],
    secondaryMuscles: ['biceps'],
    equipment: ['barbell'],
    optionalEquipment: ['ez_bar'],
    difficulty: 'beginner',
    jointStress: { elbow: 'low', wrist: 'low' },
    defaultRestSeconds: 60,
    repRangeMin: 10,
    repRangeMax: 15,
    canBeSuperset: true,
    isUnilateral: false,
    similarExercises: ['reverse-wrist-curl', 'hammer-curl', 'wrist-curl'],
    goodForDropSets: true,
  },
  {
    id: 'plate-pinch-hold',
    name: 'Plate Pinch Hold',
    category: 'isolation',
    movementPattern: 'isolation_pull',
    primaryMuscles: ['forearms'],
    secondaryMuscles: [],
    equipment: ['barbell'], // plates
    difficulty: 'beginner',
    jointStress: { wrist: 'low' },
    defaultRestSeconds: 60,
    repRangeMin: 1,
    repRangeMax: 1, // Time-based
    canBeSuperset: true,
    isUnilateral: false,
    similarExercises: ['farmers-carry', 'wrist-curl', 'reverse-wrist-curl'],
  },
  {
    id: 'spider-curl',
    name: 'Spider Curl',
    category: 'isolation',
    movementPattern: 'isolation_pull',
    primaryMuscles: ['biceps'],
    secondaryMuscles: [],
    equipment: ['dumbbell', 'incline_bench'],
    optionalEquipment: ['ez_bar'],
    difficulty: 'intermediate',
    jointStress: { elbow: 'low' },
    defaultRestSeconds: 60,
    repRangeMin: 8,
    repRangeMax: 15,
    canBeSuperset: true,
    isUnilateral: false,
    similarExercises: ['preacher-curl', 'concentration-curl', 'incline-dumbbell-curl'],
    goodForDropSets: true,
  },
  {
    id: 'preacher-curl-machine',
    name: 'Preacher Curl Machine',
    category: 'isolation',
    movementPattern: 'isolation_pull',
    primaryMuscles: ['biceps'],
    secondaryMuscles: [],
    equipment: ['machine'],
    difficulty: 'beginner',
    jointStress: { elbow: 'low' },
    defaultRestSeconds: 60,
    repRangeMin: 8,
    repRangeMax: 15,
    canBeSuperset: true,
    isUnilateral: false,
    similarExercises: ['preacher-curl', 'cable-curl', 'bicep-curl'],
    goodForDropSets: true,
  },
  {
    id: 'cross-body-curl',
    name: 'Cross Body Curl',
    category: 'isolation',
    movementPattern: 'isolation_pull',
    primaryMuscles: ['biceps', 'forearms'],
    secondaryMuscles: [],
    equipment: ['dumbbell'],
    difficulty: 'beginner',
    jointStress: { elbow: 'low' },
    defaultRestSeconds: 60,
    repRangeMin: 8,
    repRangeMax: 15,
    canBeSuperset: true,
    isUnilateral: true,
    similarExercises: ['hammer-curl', 'bicep-curl', 'concentration-curl'],
    goodForDropSets: true,
  },
  {
    id: 'overhead-cable-tricep-extension',
    name: 'Overhead Cable Tricep Extension',
    category: 'isolation',
    movementPattern: 'isolation_push',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    equipment: ['cable'],
    difficulty: 'beginner',
    jointStress: { elbow: 'low', shoulder: 'low' },
    defaultRestSeconds: 60,
    repRangeMin: 10,
    repRangeMax: 20,
    canBeSuperset: true,
    isUnilateral: false,
    similarExercises: ['overhead-tricep-extension', 'rope-pushdown', 'tricep-pushdown'],
    goodForDropSets: true,
  },
  {
    id: 'tricep-dip-machine',
    name: 'Tricep Dip Machine',
    category: 'compound',
    movementPattern: 'isolation_push',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['chest', 'front_delts'],
    equipment: ['machine'],
    difficulty: 'beginner',
    jointStress: { shoulder: 'low', elbow: 'low' },
    defaultRestSeconds: 60,
    repRangeMin: 8,
    repRangeMax: 15,
    canBeSuperset: true,
    isUnilateral: false,
    similarExercises: ['tricep-dip', 'dip', 'tricep-pushdown'],
    goodForDropSets: true,
  },
];

// =============================================================================
// ISOLATION SHOULDERS - Lateral, rear delt work
// =============================================================================

const isolationShoulders: Exercise[] = [
  {
    id: 'lateral-raise',
    name: 'Lateral Raise',
    category: 'isolation',
    movementPattern: 'isolation_shoulder',
    primaryMuscles: ['side_delts'],
    secondaryMuscles: [],
    equipment: ['dumbbell'],
    optionalEquipment: ['cable'],
    difficulty: 'beginner',
    jointStress: { shoulder: 'low' },
    defaultRestSeconds: 60,
    repRangeMin: 10,
    repRangeMax: 20,
    canBeSuperset: true,
    isUnilateral: false,
    youtubeVideoId: '3VcKaXpzqRo',
    videoStartTime: 0,
    videoEndTime: 35,
    similarExercises: ['cable-lateral-raise', 'machine-lateral-raise'],
    goodForDropSets: true,
  },
  {
    id: 'rear-delt-fly',
    name: 'Rear Delt Fly',
    category: 'isolation',
    movementPattern: 'isolation_shoulder',
    primaryMuscles: ['rear_delts'],
    secondaryMuscles: ['upper_back'],
    equipment: ['dumbbell'],
    optionalEquipment: ['cable', 'machine'],
    difficulty: 'beginner',
    jointStress: { shoulder: 'low' },
    defaultRestSeconds: 60,
    repRangeMin: 12,
    repRangeMax: 20,
    canBeSuperset: true,
    isUnilateral: false,
    youtubeVideoId: 'p1A3g6n5YzE',
    videoStartTime: 0,
    videoEndTime: 35,
    similarExercises: ['face-pull', 'reverse-pec-deck'],
    goodForDropSets: true,
  },
  {
    id: 'cable-lateral-raise',
    name: 'Cable Lateral Raise',
    category: 'isolation',
    movementPattern: 'isolation_shoulder',
    primaryMuscles: ['side_delts'],
    secondaryMuscles: [],
    equipment: ['cable'],
    difficulty: 'beginner',
    jointStress: { shoulder: 'low' },
    defaultRestSeconds: 60,
    repRangeMin: 12,
    repRangeMax: 20,
    canBeSuperset: true,
    isUnilateral: true,
    similarExercises: ['lateral-raise'],
    goodForDropSets: true,
  },
  {
    id: 'machine-lateral-raise',
    name: 'Machine Lateral Raise',
    category: 'isolation',
    movementPattern: 'isolation_shoulder',
    primaryMuscles: ['side_delts'],
    secondaryMuscles: [],
    equipment: ['machine'],
    difficulty: 'beginner',
    jointStress: { shoulder: 'low' },
    defaultRestSeconds: 60,
    repRangeMin: 12,
    repRangeMax: 20,
    canBeSuperset: true,
    isUnilateral: false,
    similarExercises: ['lateral-raise', 'cable-lateral-raise'],
    goodForDropSets: true,
  },
  {
    id: 'reverse-pec-deck',
    name: 'Reverse Pec Deck',
    category: 'isolation',
    movementPattern: 'isolation_shoulder',
    primaryMuscles: ['rear_delts'],
    secondaryMuscles: ['upper_back'],
    equipment: ['machine'],
    difficulty: 'beginner',
    jointStress: { shoulder: 'low' },
    defaultRestSeconds: 60,
    repRangeMin: 12,
    repRangeMax: 20,
    canBeSuperset: true,
    isUnilateral: false,
    similarExercises: ['rear-delt-fly', 'face-pull'],
    goodForDropSets: true,
  },
  {
    id: 'front-raise',
    name: 'Front Raise',
    category: 'isolation',
    movementPattern: 'isolation_shoulder',
    primaryMuscles: ['front_delts'],
    secondaryMuscles: [],
    equipment: ['dumbbell'],
    optionalEquipment: ['cable', 'barbell'],
    difficulty: 'beginner',
    jointStress: { shoulder: 'low' },
    defaultRestSeconds: 60,
    repRangeMin: 10,
    repRangeMax: 15,
    canBeSuperset: true,
    isUnilateral: false,
    similarExercises: ['cable-front-raise', 'lu-raise'],
    goodForDropSets: true,
  },
  {
    id: 'upright-row',
    name: 'Upright Row',
    category: 'compound',
    movementPattern: 'isolation_shoulder',
    primaryMuscles: ['side_delts', 'upper_back'],
    secondaryMuscles: ['biceps'],
    equipment: ['barbell'],
    optionalEquipment: ['dumbbell', 'cable'],
    difficulty: 'intermediate',
    jointStress: { shoulder: 'high' },
    defaultRestSeconds: 90,
    repRangeMin: 8,
    repRangeMax: 12,
    canBeSuperset: true,
    isUnilateral: false,
    similarExercises: ['lateral-raise'],
  },
  {
    id: 'shrugs',
    name: 'Shrugs',
    category: 'isolation',
    movementPattern: 'isolation_shoulder',
    primaryMuscles: ['upper_back'],
    secondaryMuscles: [],
    equipment: ['dumbbell'],
    optionalEquipment: ['barbell', 'trap_bar'],
    difficulty: 'beginner',
    jointStress: {},
    defaultRestSeconds: 60,
    repRangeMin: 10,
    repRangeMax: 20,
    canBeSuperset: true,
    isUnilateral: false,
    similarExercises: ['barbell-shrugs'],
    goodForDropSets: true,
  },
  {
    id: 'barbell-shrugs',
    name: 'Barbell Shrugs',
    category: 'isolation',
    movementPattern: 'isolation_shoulder',
    primaryMuscles: ['upper_back'],
    secondaryMuscles: ['forearms'],
    equipment: ['barbell'],
    difficulty: 'beginner',
    jointStress: {},
    defaultRestSeconds: 60,
    repRangeMin: 8,
    repRangeMax: 15,
    canBeSuperset: true,
    isUnilateral: false,
    similarExercises: ['shrugs'],
    goodForDropSets: true,
  },
  {
    id: 'cable-front-raise',
    name: 'Cable Front Raise',
    category: 'isolation',
    movementPattern: 'isolation_shoulder',
    primaryMuscles: ['front_delts'],
    secondaryMuscles: [],
    equipment: ['cable'],
    difficulty: 'beginner',
    jointStress: { shoulder: 'low' },
    defaultRestSeconds: 60,
    repRangeMin: 12,
    repRangeMax: 20,
    canBeSuperset: true,
    isUnilateral: true,
    similarExercises: ['front-raise', 'lateral-raise', 'cable-lateral-raise'],
    goodForDropSets: true,
  },
  {
    id: 'lu-raise',
    name: 'Lu Raise',
    category: 'isolation',
    movementPattern: 'isolation_shoulder',
    primaryMuscles: ['front_delts', 'side_delts'],
    secondaryMuscles: [],
    equipment: ['dumbbell'],
    difficulty: 'intermediate',
    jointStress: { shoulder: 'moderate' },
    defaultRestSeconds: 60,
    repRangeMin: 8,
    repRangeMax: 12,
    canBeSuperset: true,
    isUnilateral: false,
    similarExercises: ['front-raise', 'lateral-raise'],
  },
];

// =============================================================================
// ISOLATION LEGS - Extensions, curls, calves
// =============================================================================

const isolationLegs: Exercise[] = [
  {
    id: 'leg-curl',
    name: 'Leg Curl',
    category: 'isolation',
    movementPattern: 'isolation_leg',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: [],
    equipment: ['machine'],
    difficulty: 'beginner',
    jointStress: { knee: 'low' },
    defaultRestSeconds: 60,
    repRangeMin: 10,
    repRangeMax: 15,
    canBeSuperset: true,
    isUnilateral: false,
    youtubeVideoId: '1Tq3QdYUuHs',
    videoStartTime: 0,
    videoEndTime: 35,
    similarExercises: ['seated-leg-curl', 'nordic-curl'],
    goodForDropSets: true,
  },
  {
    id: 'leg-extension',
    name: 'Leg Extension',
    category: 'isolation',
    movementPattern: 'isolation_leg',
    primaryMuscles: ['quads'],
    secondaryMuscles: [],
    equipment: ['machine'],
    difficulty: 'beginner',
    jointStress: { knee: 'moderate' },
    defaultRestSeconds: 60,
    repRangeMin: 10,
    repRangeMax: 20,
    canBeSuperset: true,
    isUnilateral: false,
    youtubeVideoId: 'YyvSfVjQeL0',
    videoStartTime: 0,
    videoEndTime: 35,
    similarExercises: ['sissy-squat', 'leg-press-close-stance'],
    goodForDropSets: true,
  },
  {
    id: 'calf-raise',
    name: 'Calf Raise',
    category: 'isolation',
    movementPattern: 'isolation_leg',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
    equipment: ['machine'],
    optionalEquipment: ['dumbbell', 'bodyweight'],
    difficulty: 'beginner',
    jointStress: { ankle: 'low' },
    defaultRestSeconds: 45,
    repRangeMin: 12,
    repRangeMax: 20,
    canBeSuperset: true,
    isUnilateral: false,
    youtubeVideoId: 'YMmgqO8Jo-k',
    videoStartTime: 0,
    videoEndTime: 35,
    similarExercises: ['seated-calf-raise', 'standing-calf-raise', 'donkey-calf-raise', 'single-leg-calf-raise'],
    goodForDropSets: true,
    goodForPauseReps: true,
  },
  {
    id: 'seated-leg-curl',
    name: 'Seated Leg Curl',
    category: 'isolation',
    movementPattern: 'isolation_leg',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: [],
    equipment: ['machine'],
    difficulty: 'beginner',
    jointStress: { knee: 'low' },
    defaultRestSeconds: 60,
    repRangeMin: 10,
    repRangeMax: 15,
    canBeSuperset: true,
    isUnilateral: false,
    similarExercises: ['leg-curl'],
    goodForDropSets: true,
  },
  {
    id: 'seated-calf-raise',
    name: 'Seated Calf Raise',
    category: 'isolation',
    movementPattern: 'isolation_leg',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
    equipment: ['machine'],
    difficulty: 'beginner',
    jointStress: { ankle: 'low' },
    defaultRestSeconds: 45,
    repRangeMin: 12,
    repRangeMax: 20,
    canBeSuperset: true,
    isUnilateral: false,
    similarExercises: ['calf-raise', 'standing-calf-raise'],
    goodForDropSets: true,
    goodForPauseReps: true,
  },
  {
    id: 'standing-calf-raise',
    name: 'Standing Calf Raise',
    category: 'isolation',
    movementPattern: 'isolation_leg',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
    equipment: ['machine'],
    optionalEquipment: ['smith_machine'],
    difficulty: 'beginner',
    jointStress: { ankle: 'low' },
    defaultRestSeconds: 45,
    repRangeMin: 10,
    repRangeMax: 20,
    canBeSuperset: true,
    isUnilateral: false,
    similarExercises: ['calf-raise', 'seated-calf-raise'],
    goodForDropSets: true,
    goodForPauseReps: true,
  },
  {
    id: 'nordic-curl',
    name: 'Nordic Curl',
    category: 'isolation',
    movementPattern: 'isolation_leg',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: [],
    equipment: ['bodyweight'],
    difficulty: 'advanced',
    jointStress: { knee: 'moderate' },
    defaultRestSeconds: 120,
    repRangeMin: 3,
    repRangeMax: 10,
    canBeSuperset: false,
    isUnilateral: false,
    similarExercises: ['leg-curl'],
    easierVariation: 'leg-curl',
  },
  {
    id: 'hip-adduction',
    name: 'Hip Adduction',
    category: 'isolation',
    movementPattern: 'isolation_leg',
    primaryMuscles: ['adductors'],
    secondaryMuscles: [],
    equipment: ['machine'],
    optionalEquipment: ['cable'],
    difficulty: 'beginner',
    jointStress: { hip: 'low' },
    defaultRestSeconds: 60,
    repRangeMin: 12,
    repRangeMax: 20,
    canBeSuperset: true,
    isUnilateral: false,
    similarExercises: ['copenhagen-plank'],
    goodForDropSets: true,
  },
  {
    id: 'hip-abduction',
    name: 'Hip Abduction',
    category: 'isolation',
    movementPattern: 'isolation_leg',
    primaryMuscles: ['abductors', 'glutes'],
    secondaryMuscles: [],
    equipment: ['machine'],
    optionalEquipment: ['cable', 'resistance_band'],
    difficulty: 'beginner',
    jointStress: { hip: 'low' },
    defaultRestSeconds: 60,
    repRangeMin: 12,
    repRangeMax: 20,
    canBeSuperset: true,
    isUnilateral: false,
    similarExercises: ['side-lying-hip-raise'],
    goodForDropSets: true,
  },
  {
    id: 'glute-kickback',
    name: 'Glute Kickback',
    category: 'isolation',
    movementPattern: 'isolation_leg',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: ['cable'],
    optionalEquipment: ['machine'],
    difficulty: 'beginner',
    jointStress: { hip: 'low' },
    defaultRestSeconds: 60,
    repRangeMin: 12,
    repRangeMax: 20,
    canBeSuperset: true,
    isUnilateral: true,
    similarExercises: ['hip-thrust', 'glute-bridge'],
    goodForDropSets: true,
  },
  {
    id: 'donkey-calf-raise',
    name: 'Donkey Calf Raise',
    category: 'isolation',
    movementPattern: 'isolation_leg',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
    equipment: ['machine'],
    difficulty: 'intermediate',
    jointStress: { ankle: 'low' },
    defaultRestSeconds: 60,
    repRangeMin: 12,
    repRangeMax: 20,
    canBeSuperset: true,
    isUnilateral: false,
    similarExercises: ['calf-raise', 'standing-calf-raise', 'single-leg-calf-raise', 'calf-press-leg-press'],
    goodForDropSets: true,
    goodForPauseReps: true,
  },
  {
    id: 'tibialis-raise',
    name: 'Tibialis Raise',
    category: 'isolation',
    movementPattern: 'isolation_leg',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
    equipment: ['bodyweight'],
    optionalEquipment: ['dumbbell'],
    difficulty: 'beginner',
    jointStress: { ankle: 'low' },
    defaultRestSeconds: 45,
    repRangeMin: 15,
    repRangeMax: 25,
    canBeSuperset: true,
    isUnilateral: false,
    similarExercises: ['calf-raise', 'single-leg-calf-raise'],
  },
  {
    id: 'single-leg-leg-press',
    name: 'Single Leg Leg Press',
    category: 'compound',
    movementPattern: 'isolation_leg',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: ['leg_press'],
    difficulty: 'intermediate',
    jointStress: { knee: 'moderate' },
    defaultRestSeconds: 90,
    repRangeMin: 8,
    repRangeMax: 15,
    canBeSuperset: false,
    isUnilateral: true,
    similarExercises: ['leg-press', 'bulgarian-split-squat'],
  },
  {
    id: 'single-leg-calf-raise',
    name: 'Single Leg Calf Raise',
    category: 'isolation',
    movementPattern: 'isolation_leg',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
    equipment: ['bodyweight'],
    optionalEquipment: ['dumbbell'],
    difficulty: 'beginner',
    jointStress: { ankle: 'low' },
    defaultRestSeconds: 45,
    repRangeMin: 10,
    repRangeMax: 20,
    canBeSuperset: true,
    isUnilateral: true,
    similarExercises: ['calf-raise', 'standing-calf-raise', 'seated-calf-raise'],
    goodForPauseReps: true,
  },
  {
    id: 'calf-press-leg-press',
    name: 'Calf Press on Leg Press',
    category: 'isolation',
    movementPattern: 'isolation_leg',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
    equipment: ['leg_press'],
    difficulty: 'beginner',
    jointStress: { ankle: 'low', knee: 'low' },
    defaultRestSeconds: 45,
    repRangeMin: 10,
    repRangeMax: 20,
    canBeSuperset: true,
    isUnilateral: false,
    similarExercises: ['standing-calf-raise', 'calf-raise', 'seated-calf-raise'],
    goodForDropSets: true,
    goodForPauseReps: true,
  },
  {
    id: 'leg-press-close-stance',
    name: 'Leg Press Close Stance',
    category: 'compound',
    movementPattern: 'isolation_leg',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes'],
    equipment: ['leg_press'],
    difficulty: 'beginner',
    jointStress: { knee: 'moderate' },
    defaultRestSeconds: 120,
    repRangeMin: 8,
    repRangeMax: 15,
    canBeSuperset: false,
    isUnilateral: false,
    similarExercises: ['leg-press', 'hack-squat', 'leg-extension'],
    goodForDropSets: true,
  },
];

// =============================================================================
// CORE - Abs and obliques
// =============================================================================

const coreExercises: Exercise[] = [
  {
    id: 'plank',
    name: 'Plank',
    category: 'isolation',
    movementPattern: 'core',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['obliques'],
    equipment: ['bodyweight'],
    difficulty: 'beginner',
    jointStress: {},
    defaultRestSeconds: 60,
    repRangeMin: 1,
    repRangeMax: 1, // Time-based
    canBeSuperset: true,
    isUnilateral: false,
    youtubeVideoId: 'ASdvN_XEl_c',
    videoStartTime: 0,
    videoEndTime: 35,
    similarExercises: ['side-plank', 'dead-bug'],
  },
  {
    id: 'hanging-leg-raise',
    name: 'Hanging Leg Raise',
    category: 'isolation',
    movementPattern: 'core',
    primaryMuscles: ['abs', 'hip_flexors'],
    secondaryMuscles: [],
    equipment: ['pull_up_bar'],
    difficulty: 'intermediate',
    jointStress: { shoulder: 'low' },
    defaultRestSeconds: 60,
    repRangeMin: 6,
    repRangeMax: 15,
    canBeSuperset: true,
    isUnilateral: false,
    youtubeVideoId: 'Pr1ieGZ5atk',
    videoStartTime: 0,
    videoEndTime: 35,
    similarExercises: ['lying-leg-raise', 'knee-raise'],
    easierVariation: 'knee-raise',
    harderVariation: 'toes-to-bar',
  },
  {
    id: 'cable-crunch',
    name: 'Cable Crunch',
    category: 'isolation',
    movementPattern: 'core',
    primaryMuscles: ['abs'],
    secondaryMuscles: [],
    equipment: ['cable'],
    difficulty: 'beginner',
    jointStress: {},
    defaultRestSeconds: 60,
    repRangeMin: 10,
    repRangeMax: 20,
    canBeSuperset: true,
    isUnilateral: false,
    youtubeVideoId: 'AV5PmZJIrrw',
    videoStartTime: 0,
    videoEndTime: 35,
    similarExercises: ['crunch', 'ab-wheel'],
    goodForDropSets: true,
  },
  {
    id: 'crunch',
    name: 'Crunch',
    category: 'isolation',
    movementPattern: 'core',
    primaryMuscles: ['abs'],
    secondaryMuscles: [],
    equipment: ['bodyweight'],
    difficulty: 'beginner',
    jointStress: {},
    defaultRestSeconds: 45,
    repRangeMin: 12,
    repRangeMax: 25,
    canBeSuperset: true,
    isUnilateral: false,
    similarExercises: ['cable-crunch', 'sit-up'],
  },
  {
    id: 'ab-wheel',
    name: 'Ab Wheel',
    category: 'isolation',
    movementPattern: 'core',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['lats', 'triceps'],
    equipment: ['bodyweight'],
    difficulty: 'intermediate',
    jointStress: { lower_back: 'moderate', shoulder: 'low' },
    defaultRestSeconds: 90,
    repRangeMin: 6,
    repRangeMax: 15,
    canBeSuperset: true,
    isUnilateral: false,
    similarExercises: ['cable-crunch', 'plank'],
  },
  {
    id: 'russian-twist',
    name: 'Russian Twist',
    category: 'isolation',
    movementPattern: 'core',
    primaryMuscles: ['obliques', 'abs'],
    secondaryMuscles: ['hip_flexors'],
    equipment: ['bodyweight'],
    optionalEquipment: ['dumbbell', 'kettlebell'],
    difficulty: 'beginner',
    jointStress: {},
    defaultRestSeconds: 45,
    repRangeMin: 10,
    repRangeMax: 20,
    canBeSuperset: true,
    isUnilateral: false,
    similarExercises: ['cable-woodchop', 'pallof-press'],
  },
  {
    id: 'side-plank',
    name: 'Side Plank',
    category: 'isolation',
    movementPattern: 'core',
    primaryMuscles: ['obliques'],
    secondaryMuscles: ['abs'],
    equipment: ['bodyweight'],
    difficulty: 'beginner',
    jointStress: { shoulder: 'low' },
    defaultRestSeconds: 45,
    repRangeMin: 1,
    repRangeMax: 1, // Time-based
    canBeSuperset: true,
    isUnilateral: true,
    similarExercises: ['plank', 'pallof-press'],
  },
  {
    id: 'pallof-press',
    name: 'Pallof Press',
    category: 'isolation',
    movementPattern: 'core',
    primaryMuscles: ['obliques', 'abs'],
    secondaryMuscles: [],
    equipment: ['cable'],
    optionalEquipment: ['resistance_band'],
    difficulty: 'beginner',
    jointStress: {},
    defaultRestSeconds: 45,
    repRangeMin: 10,
    repRangeMax: 15,
    canBeSuperset: true,
    isUnilateral: true,
    similarExercises: ['side-plank', 'cable-woodchop'],
  },
  {
    id: 'cable-woodchop',
    name: 'Cable Woodchop',
    category: 'isolation',
    movementPattern: 'core',
    primaryMuscles: ['obliques'],
    secondaryMuscles: ['abs', 'front_delts'],
    equipment: ['cable'],
    difficulty: 'beginner',
    jointStress: {},
    defaultRestSeconds: 60,
    repRangeMin: 10,
    repRangeMax: 15,
    canBeSuperset: true,
    isUnilateral: true,
    similarExercises: ['russian-twist', 'pallof-press'],
  },
  {
    id: 'dead-bug',
    name: 'Dead Bug',
    category: 'isolation',
    movementPattern: 'core',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['hip_flexors'],
    equipment: ['bodyweight'],
    difficulty: 'beginner',
    jointStress: {},
    defaultRestSeconds: 45,
    repRangeMin: 8,
    repRangeMax: 15,
    canBeSuperset: true,
    isUnilateral: false,
    similarExercises: ['bird-dog', 'plank'],
  },
  {
    id: 'bird-dog',
    name: 'Bird Dog',
    category: 'isolation',
    movementPattern: 'core',
    primaryMuscles: ['abs', 'lower_back'],
    secondaryMuscles: ['glutes'],
    equipment: ['bodyweight'],
    difficulty: 'beginner',
    jointStress: {},
    defaultRestSeconds: 45,
    repRangeMin: 8,
    repRangeMax: 15,
    canBeSuperset: true,
    isUnilateral: false,
    similarExercises: ['dead-bug', 'plank'],
  },
  {
    id: 'lying-leg-raise',
    name: 'Lying Leg Raise',
    category: 'isolation',
    movementPattern: 'core',
    primaryMuscles: ['abs', 'hip_flexors'],
    secondaryMuscles: [],
    equipment: ['bodyweight'],
    difficulty: 'beginner',
    jointStress: { lower_back: 'low' },
    defaultRestSeconds: 45,
    repRangeMin: 10,
    repRangeMax: 20,
    canBeSuperset: true,
    isUnilateral: false,
    similarExercises: ['hanging-leg-raise', 'knee-raise'],
    harderVariation: 'hanging-leg-raise',
  },
  {
    id: 'knee-raise',
    name: 'Knee Raise',
    category: 'isolation',
    movementPattern: 'core',
    primaryMuscles: ['abs', 'hip_flexors'],
    secondaryMuscles: [],
    equipment: ['pull_up_bar'],
    optionalEquipment: ['dip_station'],
    difficulty: 'beginner',
    jointStress: {},
    defaultRestSeconds: 45,
    repRangeMin: 10,
    repRangeMax: 20,
    canBeSuperset: true,
    isUnilateral: false,
    similarExercises: ['lying-leg-raise'],
    harderVariation: 'hanging-leg-raise',
  },
];

// =============================================================================
// FULL BODY / CARDIO
// =============================================================================

const fullBodyAndCardio: Exercise[] = [
  {
    id: 'clean-and-press',
    name: 'Clean and Press',
    category: 'compound',
    movementPattern: 'vertical_push',
    primaryMuscles: ['front_delts', 'quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'lower_back', 'upper_back', 'triceps'],
    equipment: ['barbell'],
    optionalEquipment: ['dumbbell', 'kettlebell'],
    difficulty: 'advanced',
    jointStress: { shoulder: 'moderate', lower_back: 'moderate', wrist: 'low' },
    defaultRestSeconds: 180,
    repRangeMin: 3,
    repRangeMax: 8,
    canBeSuperset: false,
    isUnilateral: false,
    youtubeVideoId: 'G8l_8chR5BE',
    videoStartTime: 0,
    videoEndTime: 35,
    similarExercises: ['push-press', 'overhead-press'],
    highFatigueImpact: true,
  },
  {
    id: 'kettlebell-swing',
    name: 'Kettlebell Swing',
    category: 'compound',
    movementPattern: 'hinge',
    primaryMuscles: ['glutes', 'hamstrings'],
    secondaryMuscles: ['lower_back', 'abs', 'front_delts'],
    equipment: ['kettlebell'],
    difficulty: 'intermediate',
    jointStress: { lower_back: 'moderate', hip: 'low' },
    defaultRestSeconds: 60,
    repRangeMin: 10,
    repRangeMax: 25,
    canBeSuperset: true,
    isUnilateral: false,
    youtubeVideoId: 'YSxHifyI6s8',
    videoStartTime: 0,
    videoEndTime: 35,
    similarExercises: ['cable-pull-through', 'hip-thrust'],
  },
  {
    id: 'running',
    name: 'Running',
    category: 'cardio',
    movementPattern: 'carry',
    primaryMuscles: ['quads', 'hamstrings', 'calves'],
    secondaryMuscles: ['glutes', 'hip_flexors'],
    equipment: ['bodyweight'],
    difficulty: 'beginner',
    jointStress: { knee: 'moderate', ankle: 'moderate' },
    defaultRestSeconds: 0,
    repRangeMin: 1,
    repRangeMax: 1, // Time/distance based
    canBeSuperset: false,
    isUnilateral: false,
    youtubeVideoId: 'DqZB0rYx9C8',
    videoStartTime: 0,
    videoEndTime: 35,
    similarExercises: ['cycling', 'rowing'],
  },
  {
    id: 'cycling',
    name: 'Cycling',
    category: 'cardio',
    movementPattern: 'carry',
    primaryMuscles: ['quads', 'hamstrings'],
    secondaryMuscles: ['calves', 'glutes'],
    equipment: ['machine'],
    difficulty: 'beginner',
    jointStress: { knee: 'low' },
    defaultRestSeconds: 0,
    repRangeMin: 1,
    repRangeMax: 1,
    canBeSuperset: false,
    isUnilateral: false,
    youtubeVideoId: '1VYhyppWTDc',
    videoStartTime: 0,
    videoEndTime: 35,
    similarExercises: ['running', 'rowing'],
  },
  {
    id: 'rowing',
    name: 'Rowing',
    category: 'cardio',
    movementPattern: 'horizontal_pull',
    primaryMuscles: ['lats', 'quads'],
    secondaryMuscles: ['upper_back', 'biceps', 'hamstrings', 'glutes'],
    equipment: ['machine'],
    difficulty: 'beginner',
    jointStress: { lower_back: 'low', knee: 'low' },
    defaultRestSeconds: 0,
    repRangeMin: 1,
    repRangeMax: 1,
    canBeSuperset: false,
    isUnilateral: false,
    youtubeVideoId: 'zQ82RYIFLN8',
    videoStartTime: 0,
    videoEndTime: 35,
    similarExercises: ['running', 'cycling'],
  },
  {
    id: 'farmers-carry',
    name: 'Farmers Carry',
    category: 'compound',
    movementPattern: 'carry',
    primaryMuscles: ['forearms', 'upper_back'],
    secondaryMuscles: ['abs', 'obliques', 'glutes'],
    equipment: ['dumbbell'],
    optionalEquipment: ['kettlebell', 'trap_bar'],
    difficulty: 'beginner',
    jointStress: {},
    defaultRestSeconds: 90,
    repRangeMin: 1,
    repRangeMax: 1, // Distance/time based
    canBeSuperset: false,
    isUnilateral: false,
    similarExercises: ['suitcase-carry', 'plate-pinch-hold', 'sled-push'],
  },
  {
    id: 'suitcase-carry',
    name: 'Suitcase Carry',
    category: 'compound',
    movementPattern: 'carry',
    primaryMuscles: ['obliques', 'forearms'],
    secondaryMuscles: ['abs', 'upper_back'],
    equipment: ['dumbbell'],
    optionalEquipment: ['kettlebell'],
    difficulty: 'beginner',
    jointStress: {},
    defaultRestSeconds: 90,
    repRangeMin: 1,
    repRangeMax: 1,
    canBeSuperset: false,
    isUnilateral: true,
    similarExercises: ['farmers-carry'],
  },
  {
    id: 'burpee',
    name: 'Burpee',
    category: 'compound',
    movementPattern: 'core',
    primaryMuscles: ['chest', 'quads'],
    secondaryMuscles: ['front_delts', 'triceps', 'abs', 'glutes'],
    equipment: ['bodyweight'],
    difficulty: 'intermediate',
    jointStress: { wrist: 'low', shoulder: 'low' },
    defaultRestSeconds: 60,
    repRangeMin: 5,
    repRangeMax: 20,
    canBeSuperset: false,
    isUnilateral: false,
    similarExercises: ['mountain-climber'],
    highFatigueImpact: true,
  },
  {
    id: 'mountain-climber',
    name: 'Mountain Climber',
    category: 'compound',
    movementPattern: 'core',
    primaryMuscles: ['abs', 'hip_flexors'],
    secondaryMuscles: ['quads', 'front_delts'],
    equipment: ['bodyweight'],
    difficulty: 'beginner',
    jointStress: { wrist: 'low' },
    defaultRestSeconds: 45,
    repRangeMin: 10,
    repRangeMax: 30,
    canBeSuperset: true,
    isUnilateral: false,
    similarExercises: ['burpee', 'plank'],
  },
  {
    id: 'thruster',
    name: 'Thruster',
    category: 'compound',
    movementPattern: 'squat',
    primaryMuscles: ['quads', 'glutes', 'front_delts'],
    secondaryMuscles: ['triceps', 'abs'],
    equipment: ['barbell'],
    optionalEquipment: ['dumbbell', 'kettlebell'],
    difficulty: 'advanced',
    jointStress: { knee: 'moderate', shoulder: 'moderate', lower_back: 'moderate' },
    defaultRestSeconds: 120,
    repRangeMin: 5,
    repRangeMax: 15,
    canBeSuperset: false,
    isUnilateral: false,
    similarExercises: ['front-squat', 'overhead-press'],
    highFatigueImpact: true,
  },
  {
    id: 'sled-push',
    name: 'Sled Push',
    category: 'compound',
    movementPattern: 'carry',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['calves', 'hamstrings', 'abs'],
    equipment: ['machine'], // sled
    difficulty: 'beginner',
    jointStress: { knee: 'low', ankle: 'low' },
    defaultRestSeconds: 120,
    repRangeMin: 1,
    repRangeMax: 1, // Distance-based
    canBeSuperset: false,
    isUnilateral: false,
    similarExercises: ['farmers-carry', 'walking-lunges'],
    highFatigueImpact: true,
  },
  {
    id: 'battle-rope',
    name: 'Battle Rope',
    category: 'compound',
    movementPattern: 'core',
    primaryMuscles: ['front_delts', 'abs'],
    secondaryMuscles: ['forearms', 'upper_back', 'quads'],
    equipment: ['bodyweight'], // battle rope
    difficulty: 'beginner',
    jointStress: { shoulder: 'low', wrist: 'low' },
    defaultRestSeconds: 60,
    repRangeMin: 1,
    repRangeMax: 1, // Time-based
    canBeSuperset: false,
    isUnilateral: false,
    similarExercises: ['burpee', 'mountain-climber', 'kettlebell-swing'],
    highFatigueImpact: true,
  },
  {
    id: 'wall-ball',
    name: 'Wall Ball',
    category: 'compound',
    movementPattern: 'squat',
    primaryMuscles: ['quads', 'glutes', 'front_delts'],
    secondaryMuscles: ['triceps', 'abs'],
    equipment: ['bodyweight'], // medicine ball
    difficulty: 'beginner',
    jointStress: { knee: 'low', shoulder: 'low' },
    defaultRestSeconds: 60,
    repRangeMin: 10,
    repRangeMax: 25,
    canBeSuperset: false,
    isUnilateral: false,
    similarExercises: ['thruster', 'goblet-squat'],
    highFatigueImpact: true,
  },
  {
    id: 'turkish-get-up',
    name: 'Turkish Get-Up',
    category: 'compound',
    movementPattern: 'core',
    primaryMuscles: ['abs', 'front_delts', 'glutes'],
    secondaryMuscles: ['obliques', 'quads', 'upper_back'],
    equipment: ['kettlebell'],
    optionalEquipment: ['dumbbell'],
    difficulty: 'advanced',
    jointStress: { shoulder: 'moderate', wrist: 'low' },
    defaultRestSeconds: 120,
    repRangeMin: 1,
    repRangeMax: 5,
    canBeSuperset: false,
    isUnilateral: true,
    similarExercises: ['kettlebell-swing', 'clean-and-press'],
  },
];

// =============================================================================
// EXPORT THE COMPLETE LIBRARY
// =============================================================================

export const EXERCISE_LIBRARY: Exercise[] = [
  ...horizontalPush,
  ...verticalPush,
  ...horizontalPull,
  ...verticalPull,
  ...squatPatterns,
  ...hingePatterns,
  ...lungePatterns,
  ...isolationArms,
  ...isolationShoulders,
  ...isolationLegs,
  ...coreExercises,
  ...fullBodyAndCardio,
];

// Quick lookup by ID
export const EXERCISE_BY_ID: Record<string, Exercise> = EXERCISE_LIBRARY.reduce(
  (acc, exercise) => {
    acc[exercise.id] = exercise;
    return acc;
  },
  {} as Record<string, Exercise>
);

// Quick lookup by name (for backward compatibility)
export const EXERCISE_BY_NAME: Record<string, Exercise> = EXERCISE_LIBRARY.reduce(
  (acc, exercise) => {
    acc[exercise.name] = exercise;
    return acc;
  },
  {} as Record<string, Exercise>
);

// Get exercises by movement pattern
export function getExercisesByPattern(pattern: Exercise['movementPattern']): Exercise[] {
  return EXERCISE_LIBRARY.filter((e) => e.movementPattern === pattern);
}

// Get exercises by primary muscle
export function getExercisesByMuscle(muscle: Exercise['primaryMuscles'][number]): Exercise[] {
  return EXERCISE_LIBRARY.filter((e) => e.primaryMuscles.includes(muscle));
}

// Get exercises by equipment
export function getExercisesByEquipment(equipment: Exercise['equipment'][number]): Exercise[] {
  return EXERCISE_LIBRARY.filter((e) => e.equipment.includes(equipment));
}

// Get compound exercises only
export function getCompoundExercises(): Exercise[] {
  return EXERCISE_LIBRARY.filter((e) => e.category === 'compound');
}

// Get isolation exercises only
export function getIsolationExercises(): Exercise[] {
  return EXERCISE_LIBRARY.filter((e) => e.category === 'isolation');
}

// Log library stats
export function getLibraryStats() {
  const byPattern: Record<string, number> = {};
  const byCategory: Record<string, number> = {};
  
  EXERCISE_LIBRARY.forEach((e) => {
    byPattern[e.movementPattern] = (byPattern[e.movementPattern] || 0) + 1;
    byCategory[e.category] = (byCategory[e.category] || 0) + 1;
  });
  
  return {
    total: EXERCISE_LIBRARY.length,
    byPattern,
    byCategory,
  };
}
